export const theme = {
  colors: {
    accent: '#FF7E36',
    accentDark: '#E56F2A',
    accentSoft: '#FFF4ED',
    accentSubtle: '#FFF8F3',
    background: '#F8F9FA',
    border: '#E5E7EB',
    borderStrong: '#CBD5E1',
    card: '#FFFFFF',
    danger: '#EF4444',
    dangerSoft: '#FEF2F2',
    emerald: '#10B981',
    emeraldSoft: '#ECFDF5',
    info: '#0EA5E9',
    infoSoft: '#F0F9FF',
    muted: '#67758a',
    primary: '#FF7E36',
    primaryDark: '#E56F2A',
    primarySoft: '#FFF4ED',
    rose: '#EC4899',
    roseSoft: '#FDF2F8',
    shadow: '#0F172A',
    success: '#10B981',
    surface: '#FFFDFB',
    surfaceElevated: '#FFFFFF',
    surfaceInset: '#F1F3F5',
    text: '#1F2937',
    textInverse: '#ffffff',
    textTertiary: '#9CA3AF',
  },
  radius: {
    card: 10,
    control: 14,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  typography: {
    body: 16,
    caption: 13,
    heading: 24,
    label: 14,
    title: 18,
  },
} as const
