export const theme = {
  colors: {
    accent: '#FF9F43',
    accentDark: '#E5791F',
    accentSoft: '#FFF0DB',
    accentSubtle: '#FFF8ED',
    background: '#F4FAEE',
    border: '#DDE8D3',
    borderStrong: '#C8D9BA',
    card: '#FFFFFF',
    danger: '#EF4444',
    dangerSoft: '#FEF2F2',
    emerald: '#70B83F',
    emeraldSoft: '#EAF7D9',
    info: '#55A6FF',
    infoSoft: '#EAF4FF',
    muted: '#68786D',
    primary: '#70B83F',
    primaryDark: '#4D8F29',
    primarySoft: '#EAF7D9',
    purple: '#8B7CF6',
    purpleSoft: '#F1EFFF',
    rose: '#F36B9A',
    roseSoft: '#FFF0F6',
    shadow: '#203126',
    success: '#54A63A',
    surface: '#FFFDFC',
    surfaceElevated: '#FFFFFF',
    surfaceInset: '#EFF5EA',
    text: '#203126',
    textInverse: '#ffffff',
    textTertiary: '#9AA99D',
  },
  radius: {
    card: 8,
    control: 16,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  typography: {
    body: 16,
    caption: 13,
    heading: 24,
    label: 14,
    title: 18,
  },
} as const
