#!/usr/bin/env python3
"""
IELTS Mega Vocabulary Generator
Target: 10,000+ vocabulary words
"""

import json
import csv
from pathlib import Path
from typing import Dict, List

OUTPUT_DIR = Path(__file__).parent / "vocabulary_data"
OUTPUT_DIR.mkdir(exist_ok=True)

# ============== 大规模听力词汇库 ==============
LISTENING_SCENES = {
    'accommodation': [
        'accommodation', 'apartment', 'flat', 'house', 'dormitory', 'hostel', 'hotel', 'motel',
        'residence', 'homestay', 'rent', 'deposit', 'landlord', 'landlady', 'tenant', 'roommate',
        'bathroom', 'bedroom', 'kitchen', 'living room', 'dining room', 'garage', 'garden',
        'balcony', 'basement', 'furniture', 'furnished', 'unfurnished', 'facility', 'utilities',
        'heating', 'air conditioning', 'refrigerator', 'fridge', 'washing machine', 'microwave',
        'stove', 'oven', 'dishwasher', 'vacuum cleaner', 'lease', 'property', 'neighborhood',
        'suburb', 'downtown', 'address', 'postcode', 'meter', 'studio', 'ensuite', 'wardrobe',
        'bookshelf', 'drawer', 'cupboard', 'carpet', 'curtain', 'pillow', 'blanket', 'sheet',
        'mattress', 'sofa', 'couch', 'armchair', 'cushion', 'lamp', 'shower', 'bathtub',
        'basin', 'tap', 'sink', 'toilet', 'laundry', 'detergent', 'iron', 'ironing board',
    ],
    'education': [
        'academic', 'academy', 'admission', 'advanced', 'assignment', 'attend', 'attendance',
        'auditorium', 'bachelor', 'campus', 'certificate', 'classroom', 'compulsory', 'course',
        'credit', 'curriculum', 'degree', 'diploma', 'discipline', 'dissertation', 'doctorate',
        'dropout', 'elective', 'enroll', 'enrollment', 'essay', 'examination', 'exam', 'faculty',
        'fellowship', 'fraternity', 'freshman', 'grade', 'graduation', 'grant', 'headmaster',
        'honors', 'instructor', 'intellect', 'interdisciplinary', 'junior', 'kindergarten',
        'lecture', 'lecturer', 'literacy', 'major', 'master', 'matriculation', 'mentor', 'minor',
        'module', 'optional', 'paper', 'placement', 'postgraduate', 'prerequisite', 'preschool',
        'principal', 'professor', 'project', 'pupil', 'quiz', 'reading', 'recitation', 'register',
        'registration', 'scholarship', 'schooling', 'semester', 'seminar', 'senior', 'sophomore',
        'specialization', 'specialize', 'syllabus', 'term', 'textbook', 'thesis', 'transcript',
        'transfer', 'tuition', 'tutor', 'tutorial', 'undergraduate', 'university', 'valedictorian',
        'vocation', 'workshop', 'workbook', 'workload', 'work placement', 'apprenticeship',
    ],
    'employment': [
        'ambition', 'applicant', 'application', 'apply', 'apprentice', 'apprenticeship', 'assignment',
        'associate', 'authority', 'benefit', 'bonus', 'boss', 'candidate', 'career', 'colleague',
        'commission', 'committee', 'company', 'compensation', 'contract', 'cooperate', 'cooperation',
        'corporate', 'coworker', 'dismiss', 'dismissal', 'employ', 'employee', 'employer', 'employment',
        'executive', 'experience', 'fire', 'full-time', 'hire', 'income', 'industry', 'interview',
        'interviewer', 'job', 'labor', 'laborer', 'layoff', 'leadership', 'leave', 'manager',
        'management', 'manual', 'manufacture', 'manufacturer', 'occupation', 'offer', 'officer',
        'overtime', 'part-time', 'pension', 'position', 'profession', 'professional', 'promote',
        'promotion', 'prospective', 'qualify', 'qualification', 'recruit', 'recruitment', 'redundant',
        'resign', 'resignation', 'resume', 'retire', 'retirement', 'salary', 'shift', 'skill',
        'sick leave', 'staff', 'stipend', 'strike', 'supervisor', 'teamwork', 'temporary', 'trainee',
        'training', 'unemployed', 'unemployment', 'union', 'vacancy', 'wage', 'work', 'worker',
        'workforce', 'workplace', 'college', 'institute', 'institution', 'laboratory', 'library',
        'office', 'organization', 'personnel', 'resource', 'department', 'section', 'division',
    ],
    'travel_transport': [
        'airport', 'airline', 'arrival', 'baggage', 'boarding pass', 'booking', 'bus', 'cab',
        'cancellation', 'carry-on', 'check-in', 'coach', 'conductor', 'connection', 'customs',
        'delay', 'depart', 'departure', 'destination', 'elevator', 'escalator', 'excursion',
        'ferry', 'flight', 'gate', 'guidebook', 'hitchhike', 'immigration', 'itinerary', 'landing',
        'lounge', 'luggage', 'metro', 'platform', 'porter', 'reservation', 'return ticket',
        'round trip', 'runway', 'safety belt', 'schedule', 'single ticket', 'subway', 'takeoff',
        'terminal', 'ticket', 'timetable', 'tour', 'tourist', 'traffic', 'train', 'tram',
        'transfer', 'transit', 'transport', 'transportation', 'travel', 'trolley', 'tunnel',
        'underground', 'vehicle', 'visa', 'voyage', 'waiting room', 'youth hostel', 'passport',
        'baggage claim', 'aisle seat', 'window seat', 'economy class', 'business class',
        'first class', 'duty-free', 'baggage allowance', 'excess baggage', 'direct flight',
    ],
    'medical_health': [
        'allergy', 'ambulance', 'appointment', 'aspirin', 'blood pressure', 'capsule', 'chemist',
        'clinic', 'cough', 'dentist', 'diagnosis', 'diet', 'dosage', 'dose', 'emergency', 'exercise',
        'fever', 'flu', 'headache', 'health', 'heart attack', 'hospital', 'illness', 'immune',
        'infection', 'injury', 'insomnia', 'medicine', 'nausea', 'nurse', 'operation', 'pain',
        'painkiller', 'patient', 'pharmacy', 'physician', 'pill', 'prescription', 'receptionist',
        'recovery', 'side effect', 'stomachache', 'surgeon', 'surgery', 'symptom', 'tablet',
        'temperature', 'treatment', 'vaccination', 'vitamin', 'ward', 'X-ray', 'antibiotic',
        'pharmacist', 'warden', 'checkup', 'examination', 'wardrobe', 'wheelchair', 'stretcher',
    ],
    'shopping': [
        'bargain', 'basket', 'bill', 'brand', 'cash', 'cashier', 'catalog', 'chain store',
        'change', 'checkout', 'counter', 'coupon', 'customer', 'department store', 'discount',
        'drugstore', 'elevator', 'escalator', 'exchange', 'groceries', 'mall', 'market',
        'merchandise', 'on sale', 'opening hours', 'pay', 'payment', 'price', 'product',
        'purchase', 'receipt', 'refund', 'sale', 'shop', 'shopping center', 'shopping mall',
        'supermarket', 'trolley', 'wholesale', 'retail', 'clearance', 'redeem', 'voucher',
        'gift card', 'loyalty card', 'membership', 'warranty', 'guarantee', 'complaint',
    ],
    'banking': [
        'account', 'bank', 'bankbook', 'banking', 'bill', 'bond', 'borrow', 'branch', 'budget',
        'cash', 'cashier', 'check', 'checking account', 'coin', 'credit', 'credit card',
        'currency', 'debit', 'debt', 'deposit', 'discount', 'exchange rate', 'finance',
        'interest', 'invest', 'investment', 'loan', 'mortgage', 'overdraft', 'password',
        'PIN', 'savings', 'savings account', 'stock', 'teller', 'transfer', 'traveler check',
        'withdraw', 'withdrawal', 'ATM', 'balance', 'bank statement', 'transaction', 'fee',
    ],
    'restaurant': [
        'appetizer', 'bill', 'booking', 'buffet', 'cafe', 'canteen', 'chef', 'cook', 'course',
        'dessert', 'dining hall', 'dish', 'fast food', 'fork', 'knife', 'spoon', 'main course',
        'menu', 'napkin', 'order', 'picnic', 'plate', 'pub', 'recipe', 'reservation', 'restaurant',
        'self-service', 'snack', 'spicy', 'starter', 'tip', 'waiter', 'waitress', 'vegetarian',
        'vegan', 'beverage', 'alcohol', 'cocktail', 'wine', 'beer', 'steak', 'seafood', 'cuisine',
        'delicious', 'tasty', 'flavor', 'sour', 'sweet', 'bitter', 'salty', 'crispy', 'tender',
    ],
}

# ============== 大规模阅读词汇库 ==============
READING_TOPICS = {
    'science': [
        'accelerate', 'acceleration', 'acid', 'alkaline', 'anatomy', 'anomaly', 'antibiotic',
        'antibody', 'antigen', 'apparatus', 'application', 'artificial', 'asteroid', 'astronomy',
        'atmosphere', 'atom', 'atomic', 'bacteria', 'bacterium', 'biochemistry', 'biological',
        'biology', 'botany', 'cell', 'cellular', 'chemical', 'chemistry', 'chromosome', 'clinical',
        'clone', 'combustion', 'comet', 'compound', 'conduction', 'conductor', 'constellation',
        'contamination', 'cosmic', 'crystal', 'cytoplasm', 'data', 'debris', 'decay', 'density',
        'depletion', 'deteriorate', 'device', 'diffusion', 'digit', 'digital', 'dioxide', 'discovery',
        'dissolve', 'distill', 'DNA', 'ecosystem', 'electric', 'electrical', 'electricity',
        'electrode', 'electron', 'electronic', 'element', 'embryo', 'emit', 'energy', 'engineer',
        'engineering', 'enzyme', 'erode', 'erosion', 'evaporate', 'evaporation', 'experiment',
        'experimental', 'fiber', 'fission', 'fossil', 'frequency', 'friction', 'fuel', 'fusion',
        'galaxy', 'gas', 'gene', 'genetic', 'genetics', 'geology', 'germ', 'gravity', 'habitat',
        'hemisphere', 'heredity', 'hormone', 'host', 'hydrogen', 'hypothesis', 'immune', 'impulse',
        'infection', 'inference', 'infrared', 'innovation', 'insect', 'instrument', 'insulate',
        'insulation', 'intact', 'intensity', 'interact', 'ion', 'isotope', 'kelvin', 'kinetic',
        'laser', 'latitude', 'lens', 'lever', 'lightning', 'lime', 'liquid', 'lunar', 'magnet',
        'magnetic', 'magnify', 'mammal', 'mass', 'mechanics', 'metal', 'meteor', 'meteorology',
        'microbe', 'microbiology', 'microscope', 'microwave', 'mineral', 'mineralogy', 'molecule',
        'momentum', 'motion', 'nebula', 'nerve', 'neutron', 'nucleus', 'nutrient', 'organ',
        'organic', 'organism', 'oxide', 'oxygen', 'ozone', 'particle', 'pathogen', 'petroleum',
        'photosynthesis', 'physics', 'physiology', 'pigment', 'plasma', 'predator', 'prey',
        'pressure', 'protein', 'pulse', 'radiation', 'radioactive', 'reactor', 'refraction',
        'reproduce', 'reproduction', 'research', 'resistance', 'resonance', 'robot', 'satellite',
        'science', 'scientific', 'scientist', 'secretion', 'sediment', 'seismology', 'sensor',
        'solid', 'soluble', 'solution', 'solvent', 'species', 'specimen', 'spectrum', 'speed',
        'spore', 'stimulus', 'substance', 'sulfur', 'symbiosis', 'symptom', 'synthesis', 'synthetic',
        'technology', 'temperature', 'tension', 'terminal', 'terrain', 'terrestrial', 'theorem',
        'theory', 'thermal', 'thermometer', 'tissue', 'toxin', 'trace', 'ultraviolet', 'universe',
        'vaccine', 'vacuum', 'valve', 'vapor', 'velocity', 'venom', 'vessel', 'vibrate', 'virus',
        'voltage', 'volume', 'wavelength', 'weather', 'weight', 'zoology',
    ],
    'environment': [
        'agriculture', 'alternative', 'atmosphere', 'bio-degradable', 'biodiversity', 'biosphere',
        'carbon', 'catastrophe', 'climate', 'coastal', 'coal', 'conservation', 'contaminate',
        'dam', 'deforestation', 'degradation', 'desertification', 'destruction', 'devastation',
        'diesel', 'disaster', 'disposal', 'diversity', 'drought', 'ecologist', 'ecology',
        'ecosystem', 'emission', 'endangered', 'energy', 'environment', 'environmental', 'erosion',
        'extinct', 'extinction', 'famine', 'fertile', 'fertilizer', 'food chain', 'forest',
        'fossil fuel', 'fumes', 'global warming', 'greenhouse', 'habitat', 'hazardous', 'herbicide',
        'irreplaceable', 'landfill', 'landslide', 'marine', 'natural', 'nuclear', 'oil spill',
        'organic', 'ozone layer', 'pesticide', 'petroleum', 'pollutant', 'pollute', 'pollution',
        'population', 'preserve', 'rainforest', 'recycle', 'recyclable', 'renewable', 'reserve',
        'resource', 'sewage', 'solar', 'species', 'sustainable', 'temperature', 'toxic',
        'unleaded', 'vegetation', 'waste', 'wildlife', 'wind farm', 'acid rain', 'carbon dioxide',
        'carbon monoxide', 'climate change', 'el nino', 'la nina', 'natural gas', 'nuclear energy',
        'solar energy', 'solar panel', 'wind energy', 'green energy', 'carbon footprint',
    ],
    'health': [
        'abnormal', 'addict', 'addiction', 'addictive', 'AIDS', 'allergic', 'allergy', 'anatomy',
        'antibiotic', 'anxiety', 'appetite', 'arthritis', 'asthma', 'bacteria', 'balance', 'benign',
        'biochemistry', 'biomedical', 'blood', 'blood vessel', 'brain', 'breath', 'cancer',
        'cardiovascular', 'caries', 'carrier', 'cartilage', 'casualty', 'cavity', 'cell', 'cholesterol',
        'chronic', 'circulation', 'clinical', 'coma', 'complication', 'compound', 'congenital',
        'constipation', 'contagious', 'coronary', 'cortex', 'cough', 'curable', 'cure', 'deaf',
        'deficiency', 'dehydrate', 'dementia', 'dental', 'dentist', 'dentistry', 'depressant',
        'dermatology', 'detox', 'diabetes', 'diagnosis', 'diagnostic', 'diarrhea', 'diet', 'digest',
        'digestion', 'digestive', 'disable', 'disabled', 'disorder', 'dizzy', 'dose', 'epidemic',
        'excrete', 'exercise', 'eye', 'eyesight', 'fatigue', 'fever', 'fitness', 'flu', 'germ',
        'gland', 'health', 'healthcare', 'heart', 'heart attack', 'hormone', 'hospital', 'hygiene',
        'hypertension', 'immune', 'immunity', 'infect', 'infection', 'infectious', 'inflammation',
        'injury', 'insomnia', 'intestine', 'kidney', 'lactose', 'laser', 'liver', 'lung', 'malaria',
        'malignant', 'malnutrition', 'medical', 'medication', 'medicine', 'mental', 'metabolism',
        'microbe', 'microorganism', 'migraine', 'mutation', 'nausea', 'nerve', 'nervous', 'neurology',
        'neuron', 'obese', 'obesity', 'operation', 'organ', 'organic', 'organism', 'pain', 'painkiller',
        'paralysis', 'paralyze', 'patient', 'physician', 'physiology', 'plasma', 'poison', 'pregnant',
        'prescription', 'prevention', 'protein', 'psychiatry', 'psychology', 'pulse', 'remedy',
        'resistance', 'respiratory', 'rheumatism', 'secretion', 'seizure', 'skeleton', 'skin',
        'skull', 'spine', 'sterilize', 'stomach', 'stroke', 'surgeon', 'surgery', 'symptom',
        'syndrome', 'tablet', 'therapy', 'tissue', 'toxic', 'toxin', 'treatment', 'tumor', 'ulcer',
        'vaccinate', 'vaccination', 'vaccine', 'vein', 'virus', 'vitamin', 'vomit', 'wound',
        'yellow fever', 'blood pressure', 'blood type', 'heart disease', 'heart rate',
        'immune system', 'mental health', 'physical health', 'public health', 'side effect',
    ],
    'society': [
        'aboard', 'abroad', 'absence', 'abuse', 'academy', 'access', 'accomplish', 'accord',
        'accordance', 'account', 'acknowledge', 'acquaintance', 'acquire', 'adequate', 'adjust',
        'administer', 'administration', 'administrative', 'adolescent', 'adult', 'advocate',
        'affect', 'affection', 'affluent', 'aftermath', 'age', 'agenda', 'aggravate', 'aggressive',
        'alarm', 'alien', 'alliance', 'allocate', 'allowance', 'ally', 'alter', 'alternative',
        'amateur', 'ambassador', 'ambiguous', 'ambition', 'ambitious', 'amend', 'amendment',
        'amid', 'ancestor', 'ancient', 'anecdote', 'anniversary', 'annual', 'anticipate', 'anxiety',
        'anxious', 'apology', 'apparent', 'appeal', 'appear', 'appetite', 'applaud', 'appoint',
        'appreciate', 'approach', 'appropriate', 'approve', 'apt', 'arbitrary', 'archaeology',
        'aristocrat', 'arrogant', 'article', 'artificial', 'aspect', 'aspiration', 'assemble',
        'assembly', 'assert', 'assess', 'asset', 'assign', 'assistance', 'associate', 'association',
        'assume', 'assumption', 'assure', 'astonish', 'attach', 'attack', 'attain', 'attempt',
        'attend', 'attitude', 'attract', 'attribute', 'audience', 'author', 'authority', 'automatic',
        'available', 'aware', 'awe', 'background', 'barrier', 'behavior', 'belief', 'belong',
        'benefit', 'betray', 'bias', 'bilingual', 'billion', 'bind', 'birth', 'bless', 'bloc',
        'board', 'border', 'bound', 'boundary', 'breach', 'breakdown', 'breed', 'bribe', 'brief',
        'broad', 'broadcast', 'burden', 'bureau', 'bureaucracy', 'burst', 'campaign', 'candidate',
        'capable', 'capacity', 'capital', 'capture', 'career', 'carve', 'cast', 'casual', 'casualty',
        'cater', 'caution', 'cautious', 'cease', 'celebrate', 'census', 'ceremony', 'certainty',
        'certificate', 'challenge', 'champion', 'chance', 'channel', 'chaos', 'character',
        'characteristic', 'charge', 'charity', 'charm', 'chart', 'cherish', 'chief', 'childhood',
        'chronic', 'circumstance', 'citizen', 'citizenship', 'civic', 'civil', 'civilian',
        'civilization', 'claim', 'clarify', 'clash', 'class', 'classic', 'classify', 'clue',
        'clumsy', 'coach', 'coalition', 'coarse', 'coincide', 'collapse', 'colleague', 'collect',
        'collective', 'colonial', 'colony', 'combat', 'combine', 'comfort', 'command', 'commemorate',
        'comment', 'commerce', 'commercial', 'commission', 'commit', 'commitment', 'committee',
        'commodity', 'common', 'communicate', 'communication', 'community', 'commute', 'compact',
        'companion', 'company', 'compare', 'compatible', 'compel', 'compensate', 'compete',
        'competent', 'compile', 'complain', 'complement', 'complete', 'complex', 'complicate',
        'component', 'compose', 'composition', 'compound', 'comprehensive', 'comprise', 'compromise',
        'compulsory', 'compute', 'conceal', 'conceive', 'concentrate', 'concept', 'concern',
        'concerning', 'conclude', 'concrete', 'condemn', 'condition', 'conduct', 'confer',
        'confess', 'confidence', 'confine', 'confirm', 'conflict', 'conform', 'confront', 'confuse',
        'congratulate', 'congress', 'connect', 'conscience', 'conscious', 'consensus', 'consent',
        'consequence', 'consequently', 'consider', 'considerable', 'consist', 'consistent', 'constant',
        'constitute', 'constrain', 'construct', 'consult', 'consume', 'contact', 'contain',
        'contemplate', 'contemporary', 'contempt', 'contend', 'content', 'contest', 'context',
        'continent', 'continual', 'continue', 'continuous', 'contract', 'contradict', 'contrary',
        'contrast', 'contribute', 'controversial', 'convene', 'convenience', 'convention',
        'conventional', 'converse', 'convert', 'convey', 'convict', 'convince', 'cooperate',
        'coordinate', 'cope', 'core', 'corporate', 'corps', 'correspond', 'corresponding', 'corrupt',
        'cost', 'counsel', 'count', 'counter', 'counterpart', 'coup', 'course', 'court', 'courtesy',
        'crack', 'craft', 'crash', 'create', 'creature', 'credential', 'credit', 'crew', 'crisis',
        'criterion', 'critical', 'criticize', 'crop', 'crucial', 'crude', 'cruel', 'crush', 'cue',
        'cultivate', 'culture', 'cure', 'curiosity', 'curious', 'current', 'curriculum', 'curse',
        'curve', 'custom', 'customer', 'customs', 'cycle', 'cynical', 'daily', 'damage', 'dawn',
        'deal', 'dear', 'debate', 'decade', 'decay', 'deceit', 'deceive', 'decent', 'decide',
        'decision', 'decisive', 'declare', 'decline', 'decrease', 'dedicate', 'deem', 'default',
        'defeat', 'defect', 'defend', 'defendant', 'defense', 'defer', 'define', 'definite',
        'definition', 'degree', 'delay', 'delegate', 'delete', 'deliberate', 'delicate', 'delight',
        'deliver', 'demand', 'democracy', 'democratic', 'demonstrate', 'denial', 'denote', 'deny',
        'depart', 'department', 'departure', 'depend', 'dependent', 'depict', 'deplete', 'deposit',
        'depress', 'deprive', 'deputy', 'derive', 'descend', 'describe', 'description', 'desert',
        'deserve', 'design', 'designate', 'desirable', 'desire', 'desperate', 'despite', 'destination',
        'destroy', 'destruction', 'detach', 'detail', 'detect', 'determine', 'develop', 'device',
        'devise', 'devote', 'diagnose', 'diagram', 'dialect', 'dictate', 'differ', 'difference',
        'different', 'differentiate', 'difficult', 'difficulty', 'dignity', 'dilemma', 'dimension',
        'diminish', 'diploma', 'diplomatic', 'direct', 'direction', 'directly', 'disappear',
        'disappoint', 'disaster', 'discard', 'discern', 'discipline', 'disclose', 'discount',
        'discourage', 'discourse', 'discover', 'discreet', 'discrepancy', 'discrete', 'discriminate',
        'discuss', 'disease', 'disgrace', 'disguise', 'disgust', 'dismiss', 'disorder', 'disparity',
        'dispatch', 'displace', 'display', 'dispose', 'dispute', 'disrupt', 'dissolve', 'distance',
        'distant', 'distinct', 'distinguish', 'distort', 'distract', 'distress', 'distribute',
        'district', 'disturb', 'diverse', 'divert', 'divide', 'divine', 'division', 'divorce',
        'doctrine', 'document', 'domain', 'domestic', 'dominant', 'dominate', 'donate', 'doom',
        'dose', 'draft', 'drag', 'drain', 'dramatic', 'drastic', 'draw', 'drawback', 'drift',
        'drown', 'dual', 'dub', 'due', 'dull', 'dumb', 'dump', 'duration', 'during', 'dusk',
        'duty', 'dwell', 'dynamic', 'eager', 'earnest', 'ease', 'echo', 'eclipse', 'ecology',
        'economic', 'economy', 'ecstasy', 'edge', 'edit', 'educate', 'effect', 'effective',
        'efficiency', 'efficient', 'effort', 'ego', 'eject', 'elaborate', 'elapse', 'elastic',
        'elbow', 'elder', 'elect', 'election', 'electric', 'elegant', 'element', 'elementary',
        'elevate', 'eligible', 'eliminate', 'elite', 'eloquent', 'embark', 'embarrass', 'embassy',
        'embed', 'embody', 'embrace', 'emerge', 'emergency', 'emigrate', 'eminent', 'emit',
        'emotion', 'emphasis', 'empire', 'empirical', 'employ', 'empty', 'enclose', 'encompass',
        'encounter', 'encourage', 'endanger', 'endeavor', 'endure', 'enemy', 'energy', 'enforce',
        'engage', 'engine', 'engineer', 'enhance', 'enjoy', 'enlarge', 'enlighten', 'enormous',
        'enough', 'enrich', 'enroll', 'ensure', 'enter', 'enterprise', 'entertain', 'enthusiasm',
        'entire', 'entitle', 'entity', 'entrance', 'entrepreneur', 'entry', 'envelope', 'environment',
        'envisage', 'epidemic', 'episode', 'epoch', 'equal', 'equation', 'equator', 'equip',
        'equipment', 'equity', 'equivalent', 'era', 'erase', 'erect', 'erode', 'err', 'error',
        'erupt', 'escalate', 'escape', 'escort', 'especially', 'essay', 'essence', 'essential',
        'establish', 'estate', 'estimate', 'eternal', 'ethical', 'ethnic', 'evacuate', 'evaluate',
        'evaporate', 'eve', 'even', 'event', 'eventually', 'ever', 'evidence', 'evident', 'evil',
        'evoke', 'evolve', 'exact', 'exaggerate', 'exam', 'examine', 'example', 'exceed', 'excellent',
        'except', 'exception', 'excess', 'exchange', 'excite', 'exclaim', 'exclude', 'exclusive',
        'excuse', 'execute', 'executive', 'exempt', 'exercise', 'exhaust', 'exhibit', 'exile',
        'exist', 'exit', 'expand', 'expansion', 'expect', 'expedition', 'expel', 'expend',
        'expense', 'expensive', 'experience', 'expert', 'expertise', 'expire', 'explain', 'explicit',
        'explode', 'exploit', 'explore', 'explosion', 'export', 'expose', 'exposure', 'express',
        'extend', 'extension', 'extensive', 'extent', 'external', 'extinct', 'extinguish', 'extra',
        'extract', 'extraordinary', 'extravagant', 'extreme', 'eye', 'fabric', 'fabulous', 'face',
        'facilitate', 'facility', 'fact', 'factor', 'faculty', 'fade', 'fail', 'failure', 'fair',
        'faith', 'fake', 'fall', 'false', 'fame', 'familiar', 'famine', 'fan', 'fancy', 'fantastic',
        'fantasy', 'far', 'fare', 'farmer', 'fascinate', 'fashion', 'fast', 'fatal', 'fate',
        'father', 'fatigue', 'fault', 'favor', 'favorite', 'fear', 'feasible', 'feast', 'feat',
        'feature', 'federal', 'fee', 'feeble', 'feed', 'feedback', 'feel', 'fellow', 'female',
        'feminine', 'fence', 'fertile', 'festival', 'fetch', 'feud', 'fever', 'few', 'fiber',
        'fiction', 'field', 'fierce', 'fight', 'figure', 'file', 'filter', 'final', 'finance',
        'find', 'fine', 'finger', 'finish', 'finite', 'fire', 'firm', 'first', 'fiscal', 'fish',
        'fist', 'fit', 'fix', 'fixture', 'flag', 'flame', 'flap', 'flare', 'flash', 'flat',
        'flatter', 'flavor', 'flaw', 'flee', 'fleet', 'flesh', 'flexible', 'flick', 'flight',
        'fling', 'float', 'flock', 'flood', 'floor', 'flour', 'flourish', 'flow', 'flower',
        'flu', 'fluctuate', 'fluent', 'fluid', 'flush', 'flute', 'flux', 'fly', 'focus', 'foe',
        'fog', 'fold', 'folk', 'follow', 'fond', 'food', 'fool', 'foot', 'forbid', 'force',
        'forecast', 'forehead', 'foreign', 'foremost', 'foresee', 'forest', 'forever', 'forfeit',
        'forge', 'form', 'formal', 'format', 'formation', 'former', 'formidable', 'formula',
        'forsake', 'fort', 'forth', 'forthcoming', 'fortunate', 'fortune', 'forum', 'forward',
        'fossil', 'foster', 'foul', 'found', 'foundation', 'fountain', 'four', 'fox', 'fraction',
        'fracture', 'fragile', 'fragment', 'fragrant', 'frail', 'frame', 'framework', 'frank',
        'free', 'freedom', 'freeway', 'freeze', 'freight', 'frequency', 'frequent', 'fresh',
        'friction', 'friend', 'fright', 'frighten', 'fringe', 'frog', 'from', 'front', 'frontier',
        'frost', 'frown', 'fruit', 'frustrate', 'fuel', 'fulfill', 'full', 'fume', 'fun',
        'function', 'fund', 'fundamental', 'funeral', 'funny', 'fur', 'furious', 'furnace',
        'furnish', 'furniture', 'further', 'fury', 'fuse', 'fuss', 'future', 'gadget', 'gain',
        'galaxy', 'gallery', 'gallon', 'gamble', 'game', 'gang', 'gaol', 'gap', 'garage', 'garden',
        'garment', 'gas', 'gasp', 'gate', 'gather', 'gauge', 'gay', 'gaze', 'gear', 'gender',
        'gene', 'general', 'generate', 'generation', 'generous', 'genetic', 'genius', 'genre',
        'gentle', 'genuine', 'geography', 'gesture', 'get', 'ghost', 'giant', 'gift', 'giggle',
        'girl', 'give', 'glad', 'glance', 'glare', 'glass', 'glide', 'glimpse', 'global', 'globe',
        'gloom', 'glory', 'glove', 'glow', 'glue', 'goal', 'goat', 'gold', 'good', 'goodbye',
        'goods', 'gossip', 'govern', 'government', 'governor', 'grab', 'grace', 'grade', 'gradual',
        'graduate', 'grain', 'grand', 'grant', 'graph', 'grasp', 'grass', 'grateful', 'grave',
        'gravity', 'gray', 'great', 'greed', 'green', 'greet', 'grid', 'grief', 'grim', 'grin',
        'grind', 'grip', 'groan', 'grocery', 'gross', 'ground', 'group', 'grow', 'growth', 'guarantee',
        'guard', 'guess', 'guest', 'guide', 'guideline', 'guilt', 'guilty', 'guitar', 'gulf', 'gum',
        'gun', 'gut', 'guy', 'gym', 'habit', 'habitat', 'hail', 'hair', 'half', 'hall', 'halt',
        'ham', 'hammer', 'hand', 'handbook', 'handful', 'handle', 'handy', 'hang', 'happen',
        'happy', 'harbor', 'hard', 'harden', 'hardly', 'hardship', 'harm', 'harmony', 'harness',
        'harsh', 'harvest', 'haste', 'hat', 'hatch', 'hate', 'haul', 'haunt', 'have', 'hazard',
        'head', 'headache', 'headline', 'headquarters', 'heal', 'health', 'heap', 'hear', 'heart',
        'heat', 'heave', 'heaven', 'heavy', 'hedge', 'heel', 'height', 'heir', 'helicopter', 'hell',
        'hello', 'help', 'helpful', 'hemisphere', 'hen', 'hence', 'herald', 'herb', 'herd', 'here',
        'heritage', 'hero', 'heroine', 'heroism', 'hesitate', 'hide', 'hierarchy', 'high', 'highway',
        'hike', 'hill', 'him', 'hinder', 'hint', 'hip', 'hire', 'historian', 'historic', 'history',
        'hit', 'hobby', 'hold', 'hole', 'holiday', 'hollow', 'holy', 'home', 'homework', 'honest',
        'honey', 'honor', 'hook', 'hope', 'horizon', 'horn', 'horror', 'horse', 'hose', 'hospital',
        'host', 'hostage', 'hostile', 'hot', 'hotel', 'hour', 'house', 'household', 'housewife',
        'housework', 'housing', 'hover', 'how', 'however', 'huge', 'human', 'humble', 'humid',
        'humidity', 'humiliate', 'humor', 'hundred', 'hunger', 'hunt', 'hurdle', 'hurry', 'hurt',
        'husband', 'hut', 'hydrogen', 'hygiene', 'hypothesis', 'hysterical', 'ice', 'idea', 'ideal',
        'identical', 'identify', 'identity', 'ideology', 'idiom', 'idiot', 'idle', 'if', 'ignite',
        'ignorance', 'ignorant', 'ignore', 'ill', 'illegal', 'illness', 'illuminate', 'illusion',
        'illustrate', 'image', 'imagine', 'imitate', 'immediate', 'immense', 'immerse', 'immigrant',
        'immune', 'impact', 'impair', 'impart', 'impatient', 'imperative', 'implement', 'imply',
        'import', 'important', 'impose', 'impress', 'impression', 'impressive', 'improve', 'impulse',
        'in', 'incentive', 'incidence', 'incident', 'incline', 'include', 'income', 'incorporate',
        'increase', 'incredible', 'indeed', 'independence', 'independent', 'index', 'indicate',
        'individual', 'indoor', 'induce', 'indulge', 'industry', 'inevitable', 'infant', 'infect',
        'infer', 'inferior', 'infinite', 'inflation', 'influence', 'inform', 'information',
        'ingredient', 'inhabit', 'inherent', 'inhibit', 'initial', 'initiate', 'inject', 'injure',
        'injustice', 'ink', 'inland', 'inlet', 'inn', 'innocent', 'innovate', 'input', 'inquire',
        'insect', 'insert', 'inside', 'insight', 'insist', 'inspect', 'inspire', 'install',
        'instance', 'instant', 'instead', 'instinct', 'institute', 'institution', 'instruct',
        'instrument', 'insulate', 'insult', 'insurance', 'intact', 'intake', 'integral', 'integrate',
        'integrity', 'intellect', 'intelligent', 'intend', 'intense', 'intensity', 'intensive',
        'intent', 'intention', 'interact', 'intercourse', 'interest', 'interface', 'interfere',
        'interim', 'interior', 'intermediate', 'internal', 'international', 'Internet', 'interpret',
        'interrupt', 'intersection', 'interval', 'intervene', 'interview', 'intimate', 'intimidate',
        'into', 'intricate', 'intrigue', 'introduce', 'intrude', 'intuition', 'invade', 'invalid',
        'invaluable', 'invariably', 'invasion', 'invent', 'invest', 'investigate', 'invisible',
        'invite', 'involve', 'inward', 'iron', 'irony', 'irrespective', 'irrigate', 'irritate',
        'island', 'isolate', 'issue', 'item', 'ivory', 'jail', 'jar', 'jaw', 'jazz', 'jealous',
        'jeans', 'jet', 'jewel', 'job', 'jog', 'join', 'joint', 'joke', 'jolly', 'journal',
        'journalist', 'journey', 'joy', 'judge', 'judgment', 'judicial', 'jug', 'juice', 'jump',
        'junction', 'jungle', 'junior', 'junk', 'jury', 'just', 'justice', 'justify', 'keen',
        'keep', 'kettle', 'key', 'keyboard', 'kick', 'kid', 'kidnap', 'kidney', 'kill', 'kilo',
        'kilometer', 'kind', 'king', 'kingdom', 'kiss', 'kit', 'kitchen', 'kite', 'knee', 'kneel',
        'knife', 'knit', 'knob', 'knock', 'knot', 'know', 'knowledge', 'label', 'labor', 'laboratory',
        'lack', 'ladder', 'lady', 'lag', 'lake', 'lamb', 'lame', 'lamp', 'land', 'landlord',
        'landscape', 'lane', 'language', 'large', 'laser', 'last', 'late', 'lately', 'latent',
        'later', 'lateral', 'latest', 'latitude', 'latter', 'launch', 'laundry', 'law', 'lawn',
        'lawyer', 'lay', 'layer', 'layman', 'layout', 'lazy', 'lead', 'leader', 'leadership',
        'leading', 'leaf', 'league', 'leak', 'lean', 'leap', 'learn', 'lease', 'least', 'leather',
        'leave', 'lecture', 'left', 'legacy', 'legal', 'legend', 'legislation', 'legitimate',
        'leisure', 'lemon', 'lend', 'length', 'lens', 'less', 'lessen', 'lesson', 'lest', 'let',
        'letter', 'level', 'lever', 'liable', 'liberal', 'liberate', 'liberty', 'librarian',
        'library', 'license', 'lick', 'lid', 'lie', 'life', 'lifetime', 'lift', 'light', 'lightning',
        'like', 'likely', 'likewise', 'limb', 'limit', 'limitation', 'limited', 'limp', 'line',
        'linear', 'linen', 'linger', 'linguistic', 'link', 'lion', 'lip', 'liquid', 'liquor',
        'list', 'listen', 'literacy', 'literally', 'literary', 'literate', 'literature', 'litre',
        'litter', 'little', 'live', 'lively', 'liver', 'livestock', 'living', 'load', 'loaf',
        'loan', 'lobby', 'local', 'locality', 'locate', 'location', 'lock', 'locomotive', 'lodge',
        'log', 'logic', 'logical', 'lonely', 'long', 'longitude', 'look', 'loom', 'loop', 'loose',
        'loosen', 'lord', 'lorry', 'lose', 'loss', 'lot', 'loud', 'lounge', 'love', 'lovely',
        'low', 'loyal', 'loyalty', 'lubricate', 'luck', 'lucky', 'luggage', 'lump', 'lunar',
        'lunch', 'lung', 'lure', 'luxury', 'machine', 'machinery', 'mad', 'magazine', 'magic',
        'magistrate', 'magnet', 'magnetic', 'magnificent', 'magnify', 'magnitude', 'maid', 'mail',
        'main', 'mainland', 'maintain', 'maintenance', 'maize', 'major', 'majority', 'make',
        'male', 'mammal', 'man', 'manage', 'management', 'manager', 'manifest', 'manipulate',
        'mankind', 'manner', 'mansion', 'manual', 'manufacture', 'manufacturer', 'manuscript',
        'many', 'map', 'marathon', 'marble', 'march', 'margin', 'marginal', 'marine', 'mark',
        'market', 'marriage', 'married', 'marry', 'marsh', 'marshal', 'marvel', 'marvelous',
        'mask', 'mass', 'massive', 'master', 'masterpiece', 'mat', 'match', 'mate', 'material',
        'materialism', 'mathematical', 'mathematics', 'maths', 'matter', 'mature', 'maximum',
        'maybe', 'mayor', 'meadow', 'meal', 'mean', 'meaning', 'means', 'meantime', 'meanwhile',
        'measure', 'measurement', 'mechanic', 'mechanical', 'mechanics', 'mechanism', 'medal',
        'medical', 'medicine', 'medieval', 'meditate', 'meditation', 'medium', 'meet', 'meeting',
        'melody', 'melon', 'melt', 'member', 'membership', 'memo', 'memorial', 'memorize', 'memory',
        'menace', 'mend', 'mental', 'mention', 'menu', 'merchandise', 'merchant', 'mercury',
        'mercy', 'mere', 'merely', 'merge', 'merit', 'merry', 'mess', 'message', 'messenger',
        'metal', 'metaphor', 'metre', 'metric', 'microphone', 'microscope', 'microwave', 'midday',
        'middle', 'midnight', 'midst', 'might', 'migrate', 'mild', 'mile', 'militant', 'military',
        'milk', 'mill', 'millimetre', 'million', 'mind', 'mine', 'mineral', 'mingle', 'miniature',
        'minibus', 'minimal', 'minimize', 'minimum', 'minister', 'ministry', 'minor', 'minority',
        'minus', 'minute', 'miracle', 'mirror', 'miserable', 'misery', 'misfortune', 'mislead',
        'miss', 'missile', 'missing', 'mission', 'mist', 'mistake', 'mistress', 'misunderstand',
        'mix', 'mixture', 'moan', 'mobile', 'mobilize', 'mock', 'mode', 'model', 'moderate',
        'modern', 'modest', 'modify', 'moist', 'moisture', 'molecule', 'moment', 'momentum',
        'monarch', 'monastery', 'Monday', 'monetary', 'money', 'monitor', 'monkey', 'monopoly',
        'monotonous', 'monster', 'month', 'monument', 'mood', 'moon', 'moor', 'mop', 'moral',
        'morality', 'more', 'moreover', 'morning', 'mortal', 'mosquito', 'moss', 'most', 'mostly',
        'motel', 'mother', 'motion', 'motivate', 'motive', 'motor', 'motorway', 'mould', 'mount',
        'mountain', 'mourn', 'mouse', 'mouth', 'move', 'movement', 'movie', 'much', 'mud', 'muddy',
        'mug', 'multiple', 'multiply', 'multitude', 'municipal', 'murder', 'murmur', 'muscle',
        'muscular', 'museum', 'mushroom', 'music', 'musical', 'musician', 'must', 'mute', 'mutter',
        'mutton', 'mutual', 'mysterious', 'mystery', 'myth', 'nail', 'naked', 'name', 'namely',
        'nap', 'napkin', 'narrative', 'narrow', 'nasty', 'nation', 'national', 'nationality',
        'native', 'natural', 'naughty', 'naval', 'navigation', 'navy', 'near', 'nearby', 'nearly',
        'neat', 'necessarily', 'necessary', 'necessity', 'neck', 'necklace', 'need', 'needle',
        'negative', 'neglect', 'negligible', 'negotiate', 'neighbor', 'neighborhood', 'neither',
        'nephew', 'nerve', 'nervous', 'nest', 'net', 'network', 'neutral', 'never', 'nevertheless',
        'new', 'news', 'newspaper', 'next', 'nice', 'nickel', 'niece', 'night', 'nightmare',
        'nine', 'nineteen', 'ninety', 'nitrogen', 'no', 'noble', 'nobody', 'nod', 'noise', 'noisy',
        'nominal', 'nominate', 'none', 'nonetheless', 'nonsense', 'noon', 'nor', 'norm', 'normal',
        'normally', 'north', 'northeast', 'northern', 'northwest', 'nose', 'not', 'notable', 'note',
        'notebook', 'nothing', 'notice', 'noticeable', 'notify', 'notion', 'notorious', 'novel',
        'November', 'now', 'nowadays', 'nowhere', 'nuclear', 'nucleus', 'nuisance', 'numb',
        'number', 'numerous', 'nurse', 'nursery', 'nurture', 'nut', 'nutrition', 'nylon', 'oak',
        'oath', 'obey', 'object', 'objection', 'objective', 'obligation', 'oblige', 'obscure',
        'observation', 'observe', 'observer', 'obsess', 'obstacle', 'obtain', 'obvious', 'occasion',
        'occasional', 'occasionally', 'occupation', 'occupy', 'occur', 'occurrence', 'ocean',
        'October', 'odd', 'odds', 'odor', 'off', 'offend', 'offense', 'offensive', 'offer',
        'office', 'officer', 'official', 'offspring', 'often', 'oil', 'okay', 'old', 'olive',
        'Olympic', 'omit', 'on', 'once', 'one', 'ongoing', 'onion', 'online', 'only', 'onto',
        'open', 'opening', 'opera', 'operate', 'operation', 'operational', 'operator', 'opinion',
        'opponent', 'opportunity', 'oppose', 'opposite', 'oppress', 'opt', 'optical', 'optimistic',
        'option', 'optional', 'or', 'oral', 'orange', 'orbit', 'orchestra', 'order', 'ordinary',
        'ore', 'organ', 'organic', 'organism', 'organization', 'organize', 'orient', 'oriental',
        'origin', 'original', 'originate', 'ornament', 'orphan', 'other', 'otherwise', 'ounce',
        'our', 'ours', 'out', 'outbreak', 'outcome', 'outdoor', 'outer', 'outfit', 'outlet',
        'outline', 'outlook', 'output', 'outrage', 'outset', 'outside', 'outskirts', 'outstanding',
        'outward', 'oval', 'oven', 'over', 'overall', 'overcome', 'overdue', 'overflow',
        'overhead', 'overhear', 'overlap', 'overlook', 'overnight', 'overseas', 'oversight',
        'overtake', 'overthrow', 'overtime', 'overturn', 'overwhelm', 'owe', 'owing', 'owl',
        'own', 'owner', 'ownership', 'ox', 'oxide', 'oxygen', 'oyster', 'pace', 'pack', 'package',
        'packet', 'pact', 'pad', 'page', 'pain', 'painful', 'paint', 'painter', 'painting', 'pair',
        'palace', 'pale', 'palm', 'pan', 'panda', 'panel', 'panic', 'panorama', 'pant', 'pants',
        'paper', 'parachute', 'parade', 'paradise', 'paradox', 'paragraph', 'parallel', 'paralyze',
        'parameter', 'parasite', 'parcel', 'pardon', 'parent', 'park', 'parking', 'parliament',
        'part', 'partial', 'participate', 'particle', 'particular', 'partly', 'partner',
        'partnership', 'party', 'pass', 'passage', 'passenger', 'passion', 'passionate', 'passive',
        'passport', 'past', 'paste', 'pastime', 'pasture', 'pat', 'patch', 'patent', 'path',
        'pathetic', 'patience', 'patient', 'patriot', 'patriotic', 'patrol', 'patron', 'pattern',
        'pause', 'pave', 'pavement', 'paw', 'pay', 'payment', 'pea', 'peace', 'peaceful', 'peak',
        'peanut', 'pear', 'pearl', 'peasant', 'pebble', 'peculiar', 'pedal', 'pedestrian', 'peel',
        'peer', 'pen', 'penalty', 'pencil', 'pendulum', 'penetrate', 'peninsula', 'penny', 'pension',
        'people', 'pepper', 'per', 'perceive', 'percent', 'percentage', 'perception', 'perfect',
        'perform', 'performance', 'performer', 'perfume', 'perhaps', 'period', 'periodical',
        'perish', 'permanent', 'permeate', 'permission', 'permit', 'perpetual', 'perplex',
        'persecute', 'persevere', 'persist', 'person', 'personal', 'personality', 'personnel',
        'perspective', 'persuade', 'pessimistic', 'pest', 'pet', 'petition', 'petrol', 'petroleum',
        'petty', 'pharmacy', 'phase', 'phenomenon', 'philosopher', 'philosophy', 'phone', 'photo',
        'photograph', 'photographer', 'photography', 'phrase', 'physical', 'physician', 'physicist',
        'physics', 'physiology', 'piano', 'pick', 'pickup', 'picnic', 'picture', 'picturesque',
        'pie', 'piece', 'pierce', 'pig', 'pigeon', 'pile', 'pill', 'pillar', 'pillow', 'pilot',
        'pin', 'pinch', 'pine', 'pink', 'pint', 'pioneer', 'pipe', 'pirate', 'pistol', 'pit',
        'pitch', 'pity', 'place', 'plague', 'plain', 'plan', 'plane', 'planet', 'plant',
        'plantation', 'plaster', 'plastic', 'plate', 'plateau', 'platform', 'plausible', 'play',
        'player', 'playground', 'plea', 'plead', 'pleasant', 'please', 'pleasure', 'pledge',
        'plentiful', 'plenty', 'plight', 'plot', 'plough', 'plug', 'plumber', 'plunge', 'plural',
        'plus', 'pocket', 'poem', 'poet', 'poetry', 'point', 'poison', 'poisonous', 'poke', 'polar',
        'pole', 'police', 'policy', 'polish', 'polite', 'political', 'politician', 'politics',
        'poll', 'pollute', 'pollution', 'pond', 'ponder', 'pool', 'poor', 'pop', 'pope', 'popular',
        'population', 'porcelain', 'porch', 'pork', 'port', 'portable', 'porter', 'portion',
        'portrait', 'portray', 'pose', 'position', 'positive', 'possess', 'possession', 'possibility',
        'possible', 'possibly', 'post', 'postage', 'postcard', 'poster', 'postman', 'postpone',
        'posture', 'pot', 'potato', 'potential', 'pound', 'pour', 'poverty', 'powder', 'power',
        'powerful', 'practical', 'practically', 'practice', 'practise', 'practitioner', 'praise',
        'pray', 'prayer', 'preach', 'precaution', 'precede', 'precedent', 'precious', 'precise',
        'precision', 'preclude', 'predecessor', 'predict', 'prediction', 'predominant', 'preface',
        'prefer', 'preferable', 'preference', 'pregnant', 'prejudice', 'preliminary', 'premier',
        'premise', 'premium', 'preoccupy', 'preparation', 'prepare', 'preposition', 'prescribe',
        'prescription', 'presence', 'present', 'presentation', 'presently', 'preserve', 'preside',
        'president', 'press', 'pressure', 'prestige', 'presumably', 'presume', 'pretend', 'pretext',
        'pretty', 'prevail', 'prevalent', 'prevent', 'previous', 'prey', 'price', 'prick', 'pride',
        'priest', 'primarily', 'primary', 'prime', 'primitive', 'prince', 'princess', 'principal',
        'principle', 'print', 'prior', 'priority', 'prison', 'prisoner', 'privacy', 'private',
        'privilege', 'prize', 'probability', 'probable', 'probably', 'probe', 'problem', 'procedure',
        'proceed', 'proceeding', 'process', 'procession', 'proclaim', 'produce', 'product',
        'production', 'productive', 'productivity', 'profession', 'professional', 'professor',
        'proficiency', 'profile', 'profit', 'profitable', 'profound', 'program', 'progress',
        'progressive', 'prohibit', 'project', 'prolong', 'prominent', 'promise', 'promising',
        'promote', 'prompt', 'prone', 'pronoun', 'pronounce', 'pronunciation', 'proof', 'propagate',
        'propel', 'proper', 'property', 'prophet', 'proportion', 'proportional', 'proposal',
        'propose', 'proposition', 'prose', 'prosecute', 'prospect', 'prospective', 'prosper',
        'prosperity', 'prosperous', 'protect', 'protection', 'protective', 'protein', 'protest',
        'protocol', 'prototype', 'proud', 'prove', 'proverb', 'provide', 'provided', 'province',
        'provincial', 'provision', 'provoke', 'psychological', 'psychology', 'pub', 'public',
        'publication', 'publicity', 'publish', 'pudding', 'pull', 'pulse', 'pump', 'pumpkin',
        'punch', 'punctual', 'punish', 'pupil', 'puppet', 'purchase', 'pure', 'purify', 'purple',
        'purpose', 'purse', 'pursue', 'pursuit', 'push', 'put', 'puzzle', 'pyramid', 'qualification',
        'qualify', 'quality', 'quantify', 'quantity', 'quarrel', 'quart', 'quarter', 'queen',
        'queer', 'quest', 'question', 'questionnaire', 'queue', 'quick', 'quiet', 'quilt',
        'quit', 'quite', 'quiver', 'quiz', 'quota', 'quote', 'rabbit', 'race', 'racial', 'racism',
        'rack', 'racket', 'radar', 'radiate', 'radiation', 'radical', 'radio', 'radioactive',
        'radius', 'rag', 'rage', 'raid', 'rail', 'railroad', 'railway', 'rain', 'rainbow', 'raincoat',
        'raise', 'rake', 'rally', 'range', 'rank', 'rap', 'rapid', 'rare', 'rarely', 'rascal',
        'rat', 'rate', 'rather', 'ratio', 'rational', 'raw', 'ray', 'razor', 'reach', 'react',
        'reaction', 'reactor', 'read', 'reader', 'readily', 'reading', 'ready', 'real', 'realistic',
        'reality', 'realize', 'really', 'realm', 'reap', 'rear', 'reason', 'reasonable', 'reassure',
        'rebel', 'rebellion', 'recall', 'recede', 'receipt', 'receive', 'receiver', 'recent',
        'recently', 'reception', 'receptionist', 'receptive', 'recession', 'recipe', 'recipient',
        'reciprocal', 'recite', 'reckless', 'reckon', 'recognition', 'recognize', 'recollect',
        'recommend', 'reconcile', 'reconciliation', 'record', 'recorder', 'recover', 'recovery',
        'recreation', 'recruit', 'recruitment', 'rectangle', 'rectify', 'recur', 'recycle', 'red',
        'redeem', 'reduce', 'reduction', 'redundant', 'reed', 'refer', 'referee', 'reference',
        'refine', 'refined', 'reflect', 'reflection', 'reflex', 'reform', 'refrain', 'refresh',
        'refreshment', 'refrigerator', 'refuge', 'refugee', 'refund', 'refusal', 'refuse', 'refute',
        'regard', 'regarding', 'regardless', 'regime', 'region', 'register', 'registration',
        'regret', 'regular', 'regulate', 'regulation', 'rehearsal', 'reign', 'rein', 'reinforce',
        'reject', 'relate', 'relation', 'relationship', 'relative', 'relatively', 'relativity',
        'relax', 'relay', 'release', 'relevant', 'reliable', 'reliance', 'relief', 'relieve',
        'religion', 'religious', 'relish', 'reluctant', 'rely', 'remain', 'remainder', 'remains',
        'remark', 'remarkable', 'remedy', 'remember', 'remind', 'reminiscent', 'remote', 'removal',
        'remove', 'renaissance', 'render', 'renew', 'renewable', 'renovate', 'renown', 'rent',
        'repair', 'repay', 'repeat', 'repeatedly', 'repel', 'repertoire', 'repetition', 'replace',
        'replacement', 'represent', 'representative', 'repression', 'reproach', 'reproduce',
        'reptile', 'republic', 'republican', 'reputation', 'request', 'require', 'requirement',
        'requisite', 'rescue', 'research', 'resemblance', 'resemble', 'resent', 'reservation',
        'reserve', 'reservoir', 'reside', 'residence', 'resident', 'resign', 'resignation', 'resist',
        'resistance', 'resistant', 'resolute', 'resolution', 'resolve', 'resort', 'resource',
        'respect', 'respective', 'respond', 'response', 'responsibility', 'responsible', 'rest',
        'restaurant', 'restless', 'restore', 'restrain', 'restraint', 'restrict', 'result',
        'resultant', 'resume', 'retail', 'retain', 'retention', 'retire', 'retort', 'retreat',
        'retrieve', 'retrospect', 'return', 'reunion', 'reveal', 'revelation', 'revenge', 'revenue',
        'reverse', 'revert', 'review', 'revise', 'revive', 'revolt', 'revolution', 'revolutionary',
        'revolve', 'reward', 'rhythm', 'rib', 'ribbon', 'rice', 'rich', 'rid', 'riddle', 'ride',
        'ridge', 'ridiculous', 'rifle', 'right', 'rigid', 'ring', 'riot', 'rip', 'ripe', 'rise',
        'risk', 'risky', 'ritual', 'rival', 'river', 'road', 'roar', 'roast', 'rob', 'robbery',
        'robe', 'robot', 'robust', 'rock', 'rocket', 'rod', 'role', 'roll', 'romance', 'romantic',
        'roof', 'room', 'root', 'rope', 'rose', 'rotate', 'rotation', 'rotten', 'rough', 'round',
        'rouse', 'route', 'routine', 'row', 'royal', 'royalty', 'rub', 'rubber', 'rubbish', 'rude',
        'ruin', 'rule', 'ruler', 'rumor', 'run', 'rural', 'rush', 'rust', 'sack', 'sacred', 'sacrifice',
        'sad', 'saddle', 'safe', 'safety', 'sail', 'sailing', 'sailor', 'saint', 'sake', 'salad',
        'salary', 'sale', 'salesman', 'salient', 'salt', 'salute', 'salvation', 'same', 'sample',
        'sanction', 'sand', 'sandwich', 'satellite', 'satisfaction', 'satisfactory', 'satisfy',
        'saturate', 'Saturday', 'sauce', 'saucer', 'sausage', 'savage', 'save', 'savings', 'saw',
        'say', 'scale', 'scan', 'scandal', 'scar', 'scarce', 'scarcely', 'scare', 'scarf', 'scatter',
        'scene', 'scenery', 'scent', 'schedule', 'scheme', 'scholar', 'scholarship', 'school',
        'science', 'scientific', 'scientist', 'scissors', 'scold', 'scope', 'score', 'scorn',
        'scout', 'scramble', 'scrap', 'scrape', 'scratch', 'scream', 'screen', 'screw', 'script',
        'scrutiny', 'sculpture', 'sea', 'seal', 'search', 'season', 'seasonal', 'seat', 'second',
        'secondary', 'secret', 'secretary', 'section', 'sector', 'secure', 'security', 'see',
        'seed', 'seek', 'seem', 'seemingly', 'segment', 'segregate', 'seize', 'seldom', 'select',
        'selection', 'self', 'selfish', 'sell', 'semester', 'seminar', 'senate', 'senator', 'send',
        'senior', 'sensation', 'sense', 'sensible', 'sensitive', 'sentence', 'sentiment', 'separate',
        'sequence', 'serial', 'series', 'serious', 'servant', 'serve', 'service', 'session', 'set',
        'setback', 'setting', 'settle', 'settlement', 'several', 'severe', 'sew', 'sex', 'shabby',
        'shade', 'shadow', 'shady', 'shake', 'shall', 'shallow', 'shame', 'shape', 'share', 'shark',
        'sharp', 'shatter', 'shave', 'she', 'shed', 'sheep', 'sheer', 'sheet', 'shelf', 'shell',
        'shelter', 'shepherd', 'shield', 'shift', 'shine', 'ship', 'shipment', 'shirt', 'shiver',
        'shock', 'shoe', 'shoot', 'shop', 'shore', 'short', 'shortage', 'shortcoming', 'shortly',
        'shot', 'should', 'shoulder', 'shout', 'show', 'shower', 'shrewd', 'shrink', 'shut', 'shy',
        'sick', 'side', 'sideways', 'siege', 'sigh', 'sight', 'sightseeing', 'sign', 'signal',
        'signature', 'significance', 'significant', 'signify', 'silence', 'silent', 'silicon',
        'silk', 'silly', 'silver', 'similar', 'similarly', 'simple', 'simplicity', 'simplify',
        'simply', 'simulate', 'simultaneous', 'sin', 'since', 'sincere', 'sing', 'single', 'singular',
        'sink', 'sip', 'sir', 'sister', 'sit', 'site', 'situate', 'situation', 'size', 'skeleton',
        'sketch', 'ski', 'skill', 'skilled', 'skillful', 'skim', 'skin', 'skip', 'skirt', 'skull',
        'sky', 'skyscraper', 'slab', 'slack', 'slam', 'slap', 'slash', 'slaughter', 'slave',
        'slavery', 'sleep', 'sleeve', 'slender', 'slice', 'slide', 'slight', 'slim', 'slip',
        'slippery', 'slogan', 'slope', 'slot', 'slow', 'slum', 'sly', 'small', 'smart', 'smash',
        'smell', 'smile', 'smog', 'smoke', 'smooth', 'smuggle', 'snack', 'snake', 'snap', 'snatch',
        'sneak', 'sneeze', 'sniff', 'snow', 'so', 'soak', 'soap', 'soar', 'sob', 'sober', 'soccer',
        'social', 'socialism', 'socialist', 'society', 'sociology', 'sock', 'soda', 'sofa', 'soft',
        'software', 'soil', 'solar', 'soldier', 'sole', 'solemn', 'solid', 'solidarity', 'solitary',
        'solo', 'soluble', 'solution', 'solve', 'some', 'somebody', 'somehow', 'someone', 'something',
        'sometime', 'sometimes', 'somewhat', 'somewhere', 'son', 'song', 'soon', 'sophisticated',
        'sore', 'sorrow', 'sorry', 'sort', 'soul', 'sound', 'soup', 'sour', 'source', 'south',
        'southeast', 'southern', 'southwest', 'sovereign', 'sow', 'space', 'spacecraft', 'spade',
        'span', 'spare', 'spark', 'sparkle', 'speak', 'speaker', 'special', 'specialist',
        'specialize', 'specialty', 'species', 'specific', 'specification', 'specify', 'specimen',
        'spectacle', 'spectacular', 'spectator', 'spectrum', 'speculate', 'speech', 'speed',
        'spell', 'spelling', 'spend', 'sphere', 'spider', 'spill', 'spin', 'spine', 'spiral',
        'spirit', 'spiritual', 'spit', 'spite', 'splash', 'splendid', 'split', 'spoil', 'spokesman',
        'sponge', 'sponsor', 'spontaneous', 'spoon', 'sport', 'sportsman', 'spot', 'spouse',
        'spray', 'spread', 'spring', 'sprinkle', 'sprout', 'spur', 'spy', 'squad', 'square',
        'squeeze', 'squirrel', 'stab', 'stability', 'stable', 'stack', 'stadium', 'staff', 'stage',
        'stagger', 'stain', 'stair', 'staircase', 'stake', 'stale', 'stalk', 'stall', 'stamp',
        'stand', 'standard', 'standpoint', 'staple', 'star', 'stare', 'start', 'startle', 'starve',
        'state', 'statement', 'statesman', 'static', 'station', 'stationary', 'stationery',
        'statistic', 'statistical', 'statue', 'status', 'stay', 'steady', 'steak', 'steal',
        'steam', 'steel', 'steep', 'steer', 'stem', 'step', 'stereo', 'stereotype', 'sterling',
        'stern', 'steward', 'stick', 'sticky', 'stiff', 'still', 'stimulate', 'stimulus', 'sting',
        'stir', 'stitch', 'stock', 'stocking', 'stomach', 'stone', 'stool', 'stoop', 'stop',
        'storage', 'store', 'storey', 'storm', 'story', 'stout', 'stove', 'straight', 'straightforward',
        'strain', 'strait', 'strand', 'strange', 'stranger', 'strap', 'strategic', 'strategy',
        'straw', 'strawberry', 'stream', 'streamline', 'street', 'strength', 'strengthen', 'stress',
        'stretch', 'strict', 'stride', 'strife', 'strike', 'striking', 'string', 'strip', 'stripe',
        'strive', 'stroke', 'stroll', 'strong', 'structure', 'struggle', 'student', 'studio',
        'study', 'stuff', 'stumble', 'stump', 'stun', 'stupid', 'sturdy', 'style', 'subject',
        'subjective', 'submarine', 'submerge', 'submit', 'subordinate', 'subscribe', 'subscription',
        'subsequent', 'subside', 'subsidiary', 'subsidize', 'subsidy', 'substance', 'substantial',
        'substitute', 'subtle', 'subtract', 'suburb', 'subway', 'succeed', 'success', 'successful',
        'succession', 'successive', 'successor', 'such', 'suck', 'sudden', 'sue', 'suffer',
        'suffice', 'sufficient', 'sugar', 'suggest', 'suggestion', 'suicide', 'suit', 'suitable',
        'suite', 'sulfur', 'sum', 'summarize', 'summary', 'summer', 'summit', 'summon', 'sun',
        'Sunday', 'sunlight', 'sunny', 'sunrise', 'sunset', 'sunshine', 'super', 'superb',
        'superficial', 'superintendent', 'superior', 'superiority', 'supermarket', 'supersonic',
        'superstition', 'supervise', 'supervisor', 'supper', 'supplement', 'supply', 'support',
        'suppose', 'suppress', 'supreme', 'sure', 'surface', 'surge', 'surgeon', 'surgery',
        'surname', 'surpass', 'surplus', 'surprise', 'surrender', 'surround', 'surroundings',
        'survey', 'survival', 'survive', 'susceptible', 'suspect', 'suspend', 'suspicion',
        'suspicious', 'sustain', 'sustainable', 'swallow', 'swamp', 'swan', 'swap', 'swarm',
        'sway', 'swear', 'sweat', 'sweater', 'sweep', 'sweet', 'swell', 'swift', 'swim', 'swing',
        'Swiss', 'switch', 'sword', 'symbol', 'symmetry', 'sympathetic', 'sympathize', 'sympathy',
        'symphony', 'symposium', 'symptom', 'syndrome', 'synthesis', 'synthetic', 'system',
        'systematic', 'table', 'tablet', 'tack', 'tackle', 'tact', 'tactic', 'tag', 'tail',
        'tailor', 'take', 'tale', 'talent', 'talented', 'talk', 'tall', 'tame', 'tan', 'tangle',
        'tank', 'tap', 'tape', 'tar', 'target', 'tariff', 'task', 'taste', 'tax', 'taxi', 'tea',
        'teach', 'teacher', 'team', 'tear', 'tease', 'technical', 'technician', 'technique',
        'technology', 'tedious', 'teenager', 'telecommunications', 'telegram', 'telephone',
        'telescope', 'television', 'tell', 'temper', 'temperament', 'temperature', 'temporal',
        'temporary', 'tempt', 'temptation', 'tenant', 'tend', 'tendency', 'tender', 'tennis',
        'tense', 'tension', 'tent', 'tentative', 'term', 'terminal', 'terminate', 'terminology',
        'terrace', 'terrible', 'terrific', 'terrify', 'territory', 'terror', 'terrorist', 'test',
        'testify', 'testimony', 'text', 'textbook', 'textile', 'texture', 'than', 'thank',
        'thankful', 'that', 'the', 'theater', 'theft', 'their', 'theirs', 'them', 'theme',
        'themselves', 'then', 'theoretical', 'theory', 'therapy', 'there', 'thereafter',
        'thereby', 'therefore', 'thermal', 'thermometer', 'these', 'thesis', 'they', 'thick',
        'thief', 'thigh', 'thin', 'thing', 'think', 'third', 'thirst', 'thirsty', 'thirteen',
        'thirty', 'this', 'thorough', 'those', 'though', 'thought', 'thoughtful', 'thousand',
        'thread', 'threat', 'threaten', 'three', 'threshold', 'thrift', 'thrifty', 'thrill',
        'thrive', 'throat', 'throne', 'through', 'throughout', 'throw', 'thrust', 'thumb', 'thunder',
        'Thursday', 'thus', 'tick', 'ticket', 'tide', 'tidy', 'tie', 'tiger', 'tight', 'tile',
        'tilt', 'timber', 'time', 'timely', 'timetable', 'timid', 'tin', 'tiny', 'tip', 'tire',
        'tired', 'tiresome', 'tissue', 'title', 'to', 'toast', 'tobacco', 'today', 'toe', 'together',
        'toilet', 'token', 'tolerable', 'tolerance', 'tolerant', 'tolerate', 'toll', 'tomato',
        'tomb', 'tomorrow', 'ton', 'tone', 'tongue', 'tonight', 'too', 'tool', 'tooth', 'top',
        'topic', 'torch', 'torture', 'toss', 'total', 'touch', 'tough', 'tour', 'tourist',
        'tournament', 'tow', 'toward', 'towards', 'towel', 'tower', 'town', 'toxic', 'toy',
        'trace', 'track', 'tractor', 'trade', 'trademark', 'tradition', 'traditional', 'traffic',
        'tragedy', 'tragic', 'trail', 'train', 'training', 'trait', 'traitor', 'tram', 'tramp',
        'transaction', 'transcend', 'transfer', 'transform', 'transient', 'transistor',
        'transition', 'translate', 'translation', 'transmission', 'transmit', 'transparent',
        'transplant', 'transport', 'trap', 'trash', 'travel', 'tray', 'tread', 'treason',
        'treasure', 'treat', 'treatment', 'treaty', 'tree', 'tremble', 'tremendous', 'trench',
        'trend', 'trial', 'triangle', 'tribe', 'tribute', 'trick', 'trifle', 'trigger', 'trim',
        'trip', 'triple', 'triumph', 'trivial', 'trolley', 'troop', 'trophy', 'tropical', 'trouble',
        'troublesome', 'trousers', 'truck', 'true', 'trumpet', 'trunk', 'trust', 'truth', 'try',
        'tube', 'tuck', 'Tuesday', 'tug', 'tuition', 'tumble', 'tumor', 'tune', 'tunnel', 'turbine',
        'turbulent', 'turkey', 'turn', 'turnover', 'tutor', 'tutorial', 'twice', 'twin', 'twinkle',
        'twist', 'type', 'typewriter', 'typhoon', 'typical', 'typist', 'tyre', 'ugly', 'ultimate',
        'ultimately', 'umbrella', 'unable', 'unanimous', 'uncle', 'uncover', 'under', 'undergo',
        'undergraduate', 'underground', 'underline', 'underlie', 'undermine', 'underneath',
        'understand', 'understanding', 'undertake', 'underwear', 'undo', 'undoubtedly', 'uneasy',
        'unemployment', 'unexpected', 'unfold', 'unfortunately', 'unhappy', 'uniform', 'unify',
        'union', 'unique', 'unit', 'unite', 'unity', 'universal', 'universe', 'university', 'unknown',
        'unless', 'unlike', 'unlikely', 'unload', 'unusual', 'up', 'update', 'upgrade', 'uphold',
        'upon', 'upper', 'upright', 'upset', 'upstairs', 'up-to-date', 'upward', 'urban', 'urge',
        'urgent', 'us', 'usage', 'use', 'used', 'useful', 'useless', 'user', 'usual', 'usually',
        'utility', 'utilize', 'utmost', 'utter', 'vacant', 'vacation', 'vacuum', 'vague', 'vain',
        'valid', 'validity', 'valley', 'valuable', 'value', 'valve', 'van', 'vanish', 'vanity',
        'vapor', 'variable', 'variation', 'varied', 'variety', 'various', 'vary', 'vast', 'vault',
        'vegetable', 'vegetarian', 'vegetation', 'vehicle', 'veil', 'vein', 'velocity', 'velvet',
        'ventilate', 'venture', 'verb', 'verbal', 'verdict', 'verge', 'verify', 'versatile',
        'verse', 'version', 'versus', 'vertical', 'very', 'vessel', 'vest', 'veteran', 'veto',
        'via', 'viable', 'vibrate', 'vicinity', 'vicious', 'victim', 'victory', 'video', 'view',
        'viewpoint', 'vigorous', 'village', 'villain', 'vinegar', 'violate', 'violence', 'violent',
        'violet', 'violin', 'virtual', 'virtually', 'virtue', 'virus', 'visa', 'visible', 'vision',
        'visit', 'visitor', 'visual', 'vital', 'vitamin', 'vivid', 'vocabulary', 'vocal', 'voice',
        'void', 'volcano', 'volleyball', 'volt', 'voltage', 'volume', 'voluntary', 'volunteer',
        'vote', 'voter', 'vow', 'vowel', 'voyage', 'vulgar', 'vulnerable', 'wage', 'wagon', 'waist',
        'wait', 'waiter', 'waitress', 'wake', 'waken', 'walk', 'wall', 'wallet', 'wander', 'want',
        'war', 'ward', 'wardrobe', 'warehouse', 'warfare', 'warm', 'warmth', 'warn', 'warning',
        'warrant', 'warrior', 'wash', 'waste', 'watch', 'water', 'waterproof', 'watt', 'wave',
        'wax', 'way', 'we', 'weak', 'weaken', 'weakness', 'wealth', 'wealthy', 'weapon', 'wear',
        'weary', 'weather', 'weave', 'wedding', 'wedge', 'Wednesday', 'weed', 'week', 'weekday',
        'weekend', 'weekly', 'weep', 'weigh', 'weight', 'weird', 'welcome', 'weld', 'welfare',
        'well', 'well-known', 'west', 'western', 'wet', 'whale', 'what', 'whatever', 'whatsoever',
        'wheat', 'wheel', 'when', 'whenever', 'where', 'whereas', 'wherever', 'whether', 'which',
        'whichever', 'while', 'whip', 'whisper', 'whistle', 'white', 'who', 'whoever', 'whole',
        'wholly', 'whom', 'whose', 'why', 'wicked', 'wide', 'widespread', 'widow', 'width', 'wife',
        'wild', 'will', 'willing', 'win', 'wind', 'window', 'windy', 'wine', 'wing', 'winner',
        'winter', 'wipe', 'wire', 'wisdom', 'wise', 'wish', 'wit', 'with', 'withdraw', 'within',
        'without', 'withstand', 'witness', 'wolf', 'woman', 'wonder', 'wonderful', 'wood', 'wooden',
        'wool', 'word', 'work', 'worker', 'workman', 'workshop', 'world', 'worldwide', 'worm',
        'worry', 'worship', 'worth', 'worthwhile', 'worthy', 'would', 'wound', 'wrap', 'wrath',
        'wreath', 'wreck', 'wrench', 'wrestle', 'wretched', 'wrinkle', 'wrist', 'write', 'writer',
        'writing', 'wrong', 'X-ray', 'yacht', 'yard', 'yawn', 'year', 'yearly', 'yell', 'yellow',
        'yes', 'yesterday', 'yet', 'yield', 'you', 'young', 'youngster', 'your', 'yours',
        'yourself', 'youth', 'zeal', 'zebra', 'zero', 'zone', 'zoo', 'zoology'
    ],
}

# ============== 生成函数 ==============

def generate_listening_vocabulary():
    """生成听力词汇"""
    words = []
    for scene, word_list in LISTENING_SCENES.items():
        for word in word_list:
            words.append({
                'word': word,
                'translation': '',  # 将在后续处理
                'pos': 'noun',
                'category': f'listening_{scene}',
                'level': '5',
                'frequency': 70,
                'source': 'IELTS_Listening'
            })
    return words

def generate_reading_vocabulary():
    """生成阅读词汇"""
    words = []
    for topic, word_list in READING_TOPICS.items():
        for word in word_list:
            words.append({
                'word': word,
                'translation': '',
                'pos': 'noun',
                'category': f'reading_{topic}',
                'level': '6',
                'frequency': 65,
                'source': 'IELTS_Reading'
            })
    return words

def export_to_json(data: List[Dict], filename: str):
    """导出为JSON"""
    filepath = OUTPUT_DIR / filename
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  - Exported: {filepath} ({len(data)} words)")
    return filepath

def generate_all_vocabulary():
    """生成所有词汇"""
    print("=" * 70)
    print("IELTS Mega Vocabulary Generator")
    print("=" * 70)

    print("\n[1/2] Generating listening vocabulary...")
    listening_words = generate_listening_vocabulary()
    print(f"  - Generated {len(listening_words)} listening words")

    print("\n[2/2] Generating reading vocabulary...")
    reading_words = generate_reading_vocabulary()
    print(f"  - Generated {len(reading_words)} reading words")

    all_words = listening_words + reading_words

    print(f"\n[STATS] Total words: {len(all_words)}")

    # 导出
    print("\n" + "-" * 50)
    print("Exporting files...")
    print("-" * 50)

    export_to_json(all_words, 'ielts_vocabulary_mega.json')

    return all_words

if __name__ == '__main__':
    generate_all_vocabulary()
