def seed_stats_contract_data(user_id: int):
    older_days = [
        utc_dt(2026, 3, 22 + day_offset, 2)
        for day_offset in range(7)
    ]
    newer_days = [
        utc_dt(2026, 3, 29 + day_offset, 2)
        for day_offset in range(3)
    ] + [
        utc_dt(2026, 4, 1 + day_offset, 2)
        for day_offset in range(3)
    ]

    for started_at in older_days:
        add_study_session(
            user_id=user_id,
            mode='listening',
            book_id='book-a',
            chapter_id='1',
            started_at=started_at,
            words_studied=10,
            correct_count=4,
            wrong_count=6,
            duration_seconds=100,
        )

    for started_at in newer_days:
        add_study_session(
            user_id=user_id,
            mode='listening',
            book_id='book-a',
            chapter_id='1',
            started_at=started_at,
            words_studied=10,
            correct_count=9,
            wrong_count=1,
            duration_seconds=100,
        )

    add_study_session(
        user_id=user_id,
        mode='meaning',
        book_id='book-b',
        chapter_id='2',
        started_at=utc_dt(2026, 4, 4, 3),
        words_studied=8,
        correct_count=4,
        wrong_count=4,
        duration_seconds=80,
    )
    add_study_session(
        user_id=user_id,
        mode='quickmemory',
        book_id='book-b',
        chapter_id='2',
        started_at=utc_dt(2026, 4, 4, 3, 30),
        words_studied=6,
        correct_count=5,
        wrong_count=1,
        duration_seconds=60,
    )

    db.session.add_all([
        UserChapterProgress(
            user_id=user_id,
            book_id='book-a',
            chapter_id=1,
            words_learned=7,
            correct_count=5,
            wrong_count=1,
            is_completed=True,
            updated_at=utc_dt(2026, 4, 4, 1),
        ),
        UserChapterProgress(
            user_id=user_id,
            book_id='book-b',
            chapter_id=2,
            words_learned=5,
            correct_count=2,
            wrong_count=3,
            is_completed=False,
            updated_at=utc_dt(2026, 4, 3, 1),
        ),
        UserChapterModeProgress(
            user_id=user_id,
            book_id='book-a',
            chapter_id=1,
            mode='listening',
            correct_count=7,
            wrong_count=3,
            is_completed=True,
            updated_at=utc_dt(2026, 4, 4, 1),
        ),
        UserChapterModeProgress(
            user_id=user_id,
            book_id='book-b',
            chapter_id=2,
            mode='meaning',
            correct_count=2,
            wrong_count=3,
            is_completed=False,
            updated_at=utc_dt(2026, 4, 3, 1),
        ),
    ])

    quick_memory_rows = [
        UserQuickMemoryRecord(
            user_id=user_id,
            word='kind',
            book_id='book-b',
            chapter_id='2',
            status='known',
            first_seen=epoch_ms(utc_dt(2026, 4, 3, 17)),
            last_seen=epoch_ms(utc_dt(2026, 4, 3, 17, 5)),
            known_count=1,
            unknown_count=0,
            next_review=epoch_ms(utc_dt(2026, 4, 5, 4)),
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='effect',
            book_id='book-b',
            chapter_id='2',
            status='known',
            first_seen=epoch_ms(utc_dt(2026, 4, 2, 1)),
            last_seen=epoch_ms(utc_dt(2026, 4, 4, 1)),
            known_count=2,
            unknown_count=0,
            next_review=epoch_ms(utc_dt(2026, 4, 4, 0)),
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='alpha',
            book_id='book-a',
            chapter_id='1',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 1)),
            last_seen=epoch_ms(utc_dt(2026, 4, 3, 12)),
            known_count=0,
            unknown_count=2,
            next_review=epoch_ms(utc_dt(2026, 4, 3, 23)),
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='beta',
            book_id='book-a',
            chapter_id='1',
            status='known',
            first_seen=epoch_ms(utc_dt(2026, 4, 2, 2)),
            last_seen=epoch_ms(utc_dt(2026, 4, 3, 12)),
            known_count=1,
            unknown_count=1,
            next_review=epoch_ms(utc_dt(2026, 4, 6, 3)),
            fuzzy_count=2,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='gamma',
            book_id='book-a',
            chapter_id='1',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 2)),
            last_seen=epoch_ms(utc_dt(2026, 4, 2, 2)),
            known_count=0,
            unknown_count=1,
            next_review=0,
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='delta',
            book_id='book-a',
            chapter_id='1',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 3)),
            last_seen=epoch_ms(utc_dt(2026, 4, 2, 3)),
            known_count=0,
            unknown_count=1,
            next_review=0,
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='epsilon',
            book_id='book-a',
            chapter_id='1',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 4)),
            last_seen=epoch_ms(utc_dt(2026, 4, 2, 4)),
            known_count=0,
            unknown_count=1,
            next_review=0,
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='zeta',
            book_id='book-b',
            chapter_id='2',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 5)),
            last_seen=epoch_ms(utc_dt(2026, 4, 2, 5)),
            known_count=0,
            unknown_count=1,
            next_review=0,
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='eta',
            book_id='book-b',
            chapter_id='2',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 6)),
            last_seen=epoch_ms(utc_dt(2026, 4, 2, 6)),
            known_count=0,
            unknown_count=1,
            next_review=0,
            fuzzy_count=0,
        ),
        UserQuickMemoryRecord(
            user_id=user_id,
            word='theta',
            book_id='book-b',
            chapter_id='2',
            status='unknown',
            first_seen=epoch_ms(utc_dt(2026, 4, 1, 7)),
            last_seen=epoch_ms(utc_dt(2026, 4, 2, 7)),
            known_count=0,
            unknown_count=1,
            next_review=0,
            fuzzy_count=0,
        ),
    ]
    db.session.add_all(quick_memory_rows)

    db.session.add_all([
        UserWrongWord(
            user_id=user_id,
            word='kind',
            phonetic='/kaɪnd/',
            pos='n.',
            definition='type',
            wrong_count=5,
            listening_wrong=1,
            meaning_wrong=4,
            dictation_wrong=0,
        ),
        UserWrongWord(
            user_id=user_id,
            word='effect',
            phonetic='/ɪˈfekt/',
            pos='n.',
            definition='result',
            wrong_count=4,
            listening_wrong=2,
            meaning_wrong=2,
            dictation_wrong=0,
        ),
    ])

    db.session.add_all([
        UserSmartWordStat(
            user_id=user_id,
            word='kind',
            listening_correct=1,
            listening_wrong=5,
            meaning_correct=2,
            meaning_wrong=7,
            dictation_correct=3,
            dictation_wrong=1,
        ),
        UserSmartWordStat(
            user_id=user_id,
            word='effect',
            listening_correct=2,
            listening_wrong=4,
            meaning_correct=1,
            meaning_wrong=5,
            dictation_correct=4,
            dictation_wrong=1,
        ),
    ])

    db.session.add_all([
        UserLearningNote(
            user_id=user_id,
            question='What is the difference between kind and type?',
            answer='kind is broader in tone.',
            word_context='kind',
            created_at=utc_dt(2026, 4, 4, 1, 10),
        ),
        UserLearningNote(
            user_id=user_id,
            question='Please explain kind and type again.',
            answer='kind is more general in this context.',
            word_context='kind',
            created_at=utc_dt(2026, 4, 4, 1, 40),
        ),
    ])

    db.session.add_all([
        UserLearningEvent(
            user_id=user_id,
            event_type='study_session',
            source='practice',
            mode='listening',
            book_id='book-a',
            chapter_id='1',
            item_count=10,
            correct_count=9,
            wrong_count=1,
            duration_seconds=100,
            occurred_at=utc_dt(2026, 4, 4, 2, 5),
        ),
        UserLearningEvent(
            user_id=user_id,
            event_type='quick_memory_review',
            source='quickmemory',
            mode='quickmemory',
            book_id='book-b',
            chapter_id='2',
            word='effect',
            item_count=1,
            correct_count=1,
            wrong_count=0,
            payload=json.dumps({'status': 'known'}, ensure_ascii=False),
            occurred_at=utc_dt(2026, 4, 4, 2, 10),
        ),
        UserLearningEvent(
            user_id=user_id,
            event_type='quick_memory_review',
            source='quickmemory',
            mode='quickmemory',
            book_id='book-a',
            chapter_id='1',
            word='alpha',
            item_count=1,
            correct_count=0,
            wrong_count=1,
            payload=json.dumps({'status': 'unknown'}, ensure_ascii=False),
            occurred_at=utc_dt(2026, 4, 4, 2, 12),
        ),
        UserLearningEvent(
            user_id=user_id,
            event_type='wrong_word_recorded',
            source='wrong_words',
            mode='meaning',
            book_id='book-b',
            chapter_id='2',
            word='kind',
            item_count=1,
            correct_count=0,
            wrong_count=1,
            occurred_at=utc_dt(2026, 4, 4, 2, 15),
        ),
        UserLearningEvent(
            user_id=user_id,
            event_type='assistant_question',
            source='assistant',
            mode='meaning',
            word='kind',
            item_count=1,
            payload=json.dumps({'question': 'How do I use kind in IELTS writing?'}, ensure_ascii=False),
            occurred_at=utc_dt(2026, 4, 4, 2, 20),
        ),
        UserLearningEvent(
            user_id=user_id,
            event_type='listening_review',
            source='practice',
            mode='listening',
            book_id='book-a',
            chapter_id='1',
            word='kind',
            item_count=1,
            correct_count=1,
            wrong_count=0,
            payload=json.dumps({'passed': True, 'source_mode': 'smart'}, ensure_ascii=False),
            occurred_at=utc_dt(2026, 4, 4, 2, 25),
        ),
        UserLearningEvent(
            user_id=user_id,
            event_type='speaking_simulation',
            source='assistant',
            mode='speaking',
            book_id='book-b',
            chapter_id='2',
            item_count=1,
            correct_count=1,
            wrong_count=0,
            payload=json.dumps({
                'part': 2,
                'topic': 'education',
                'target_words': ['kind'],
                'response_text': 'Kind feedback improves confidence.',
            }, ensure_ascii=False),
            occurred_at=utc_dt(2026, 4, 4, 2, 30),
        ),
    ])

    db.session.commit()
