import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  answerButton: {
    alignItems: 'center',
    borderRadius: theme.radius.control,
    flex: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    justifyContent: 'center',
    minHeight: 48,
  },
  answerButtonText: {
    color: theme.colors.text,
    fontWeight: '900',
  },
  answerRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  choiceButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.control,
    flexBasis: '48%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.sm,
  },
  choiceText: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '800',
    textAlign: 'center',
  },
  choiceWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  confirmButton: {
    backgroundColor: theme.colors.emeraldSoft,
  },
  definition: {
    color: theme.colors.text,
    fontSize: theme.typography.body,
    lineHeight: 23,
    marginTop: theme.spacing.sm,
  },
  exampleBox: {
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.card,
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
  },
  exampleHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
    marginTop: theme.spacing.xs,
  },
  exampleText: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    lineHeight: 20,
    marginTop: theme.spacing.xs,
  },
  exampleTitle: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  hero: {
    backgroundColor: theme.colors.surface,
  },
  heroCopy: {
    flex: 1,
  },
  heroHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.label,
    lineHeight: 20,
    marginTop: theme.spacing.xs,
  },
  heroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.md,
    justifyContent: 'space-between',
  },
  micStrip: {
    alignItems: 'center',
    backgroundColor: theme.colors.infoSoft,
    borderRadius: theme.radius.control,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    marginTop: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  micText: {
    color: theme.colors.info,
    flex: 1,
    fontSize: theme.typography.caption,
    fontWeight: '700',
  },
  modeCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 124,
    padding: theme.spacing.md,
  },
  modeCardActive: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  modeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  modeHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
    marginTop: theme.spacing.xs,
  },
  modeIcon: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.pill,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  modeIconActive: {
    backgroundColor: theme.colors.surfaceElevated,
  },
  modeLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
    marginTop: theme.spacing.sm,
  },
  progressFill: {
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    height: '100%',
  },
  progressTrack: {
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.pill,
    height: 10,
    marginTop: theme.spacing.md,
    overflow: 'hidden',
  },
  rejectButton: {
    backgroundColor: theme.colors.dangerSoft,
  },
  scoreBox: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: theme.radius.card,
    minWidth: 82,
    paddingVertical: theme.spacing.md,
  },
  scoreLabel: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  scoreValue: {
    color: theme.colors.primaryDark,
    fontSize: 24,
    fontWeight: '900',
  },
  sectionHead: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.sm,
  },
  word: {
    color: theme.colors.text,
    fontSize: 26,
    fontWeight: '900',
  },
  wordMeta: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    marginTop: theme.spacing.xs,
  },
  workbench: {
    backgroundColor: theme.colors.surfaceElevated,
  },
  workbenchTop: {
    flexDirection: 'row',
    gap: theme.spacing.xs,
  },
})
