import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  avatar: {
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    shadowColor: theme.colors.accent,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    width: 56,
  },
  avatarText: {
    color: theme.colors.textInverse,
    fontSize: 22,
    fontWeight: '900',
  },
  benefitCell: {
    flex: 1,
    gap: 4,
    paddingHorizontal: 8,
  },
  benefitDivider: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    height: 44,
    width: 1,
  },
  benefitMeta: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 12,
    fontWeight: '700',
  },
  benefitStrip: {
    alignItems: 'center',
    backgroundColor: '#17130F',
    borderRadius: theme.radius.card,
    flexDirection: 'row',
    marginBottom: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.lg,
  },
  benefitTitle: {
    color: theme.colors.textInverse,
    fontSize: 14,
    fontWeight: '900',
  },
  emptyWish: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.card,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  emptyWishText: {
    color: theme.colors.muted,
    fontSize: theme.typography.label,
    fontWeight: '700',
  },
  iconTile: {
    alignItems: 'center',
    flex: 1,
    gap: theme.spacing.xs,
    minWidth: 68,
  },
  iconTileLabel: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  iconTileMark: {
    alignItems: 'center',
    borderRadius: 20,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  identityBlock: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  identityCopy: {
    flex: 1,
  },
  identityLink: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  input: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.control,
    borderWidth: 1,
    color: theme.colors.text,
    fontSize: theme.typography.body,
    minHeight: 48,
    marginTop: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
  },
  learningRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: theme.radius.card,
    minHeight: 56,
    justifyContent: 'center',
    marginTop: theme.spacing.md,
  },
  logoutText: {
    color: theme.colors.danger,
    fontSize: theme.typography.body,
    fontWeight: '800',
  },
  moreLink: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  moreText: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  noticeText: {
    color: theme.colors.emerald,
    fontSize: theme.typography.label,
    fontWeight: '800',
    marginTop: theme.spacing.xs,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: theme.radius.control,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'center',
    minHeight: 50,
    marginTop: theme.spacing.md,
  },
  primaryButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  quickGrid: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  screen: {
    backgroundColor: theme.colors.background,
    padding: theme.spacing.lg,
    paddingBottom: 160,
  },
  scroll: {
    backgroundColor: theme.colors.background,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accentSoft,
    borderColor: 'rgba(255,126,54,0.22)',
    borderRadius: theme.radius.control,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    marginTop: theme.spacing.md,
  },
  secondaryButtonText: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionMeta: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 19,
  },
  sectionTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
  },
  settingGroup: {
    marginBottom: theme.spacing.md,
    paddingHorizontal: 0,
    paddingVertical: theme.spacing.xs,
  },
  settingLabel: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  settingLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: theme.spacing.md,
  },
  settingRight: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-end',
  },
  settingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 64,
    paddingHorizontal: theme.spacing.lg,
  },
  settingsScreen: {
    backgroundColor: theme.colors.background,
    padding: theme.spacing.lg,
    paddingBottom: 160,
  },
  settingValue: {
    color: theme.colors.textTertiary,
    fontSize: theme.typography.label,
    fontWeight: '800',
    maxWidth: 132,
  },
  surfaceCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.borderStrong,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    marginBottom: theme.spacing.md,
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  textarea: {
    minHeight: 96,
    paddingTop: theme.spacing.md,
  },
  userMeta: {
    color: theme.colors.muted,
    fontSize: theme.typography.label,
    fontWeight: '700',
    marginTop: 2,
  },
  username: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: '900',
  },
  wishCopy: {
    flex: 1,
  },
  wishMark: {
    alignItems: 'center',
    backgroundColor: theme.colors.accentSoft,
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  wishMeta: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
  },
  wishRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
    paddingVertical: theme.spacing.md,
  },
  wishTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
})
