-- IELTS Vocabulary Database Insert Statements
-- Generated: Auto-generated

INSERT INTO vocabulary (word, translation, pos, category, level, frequency) VALUES
  ('analysis', '分析', 'noun', 'academic', 7, 60),
  ('approach', '方法，接近', 'noun/verb', 'academic', 7, 55),
  ('area', '领域', 'noun', 'academic', 7, 50),
  ('assessment', '评估', 'noun', 'academic', 7, 45),
  ('assume', '假设', 'verb', 'academic', 7, 42),
  ('authority', '权威', 'noun', 'academic', 7, 40),
  ('available', '可用的', 'adjective', 'academic', 7, 65),
  ('benefit', '益处', 'noun/verb', 'academic', 7, 48),
  ('concept', '概念', 'noun', 'academic', 7, 52),
  ('consist', '由...组成', 'verb', 'academic', 7, 35),
  ('constitute', '构成', 'verb', 'academic', 7, 38),
  ('context', '上下文', 'noun', 'academic', 7, 58),
  ('contract', '合同', 'noun/verb', 'academic', 7, 30),
  ('create', '创造', 'verb', 'academic', 7, 62),
  ('data', '数据', 'noun', 'academic', 7, 70),
  ('define', '定义', 'verb', 'academic', 7, 45),
  ('derive', '推导，源自', 'verb', 'academic', 7, 40),
  ('distribute', '分配', 'verb', 'academic', 7, 42),
  ('economy', '经济', 'noun', 'academic', 7, 55),
  ('environment', '环境', 'noun', 'academic', 7, 58),
  ('establish', '建立', 'verb', 'academic', 7, 48),
  ('estimate', '估计', 'verb/noun', 'academic', 7, 44),
  ('evidence', '证据', 'noun', 'academic', 7, 56),
  ('export', '出口', 'verb/noun', 'academic', 7, 35),
  ('factor', '因素', 'noun', 'academic', 7, 50),
  ('finance', '金融', 'noun/verb', 'academic', 7, 40),
  ('formula', '公式', 'noun', 'academic', 7, 38),
  ('function', '功能', 'noun/verb', 'academic', 7, 52),
  ('identify', '识别', 'verb', 'academic', 7, 60),
  ('income', '收入', 'noun', 'academic', 7, 42),
  ('indicate', '表明', 'verb', 'academic', 7, 48),
  ('individual', '个人的', 'adjective/noun', 'academic', 7, 55),
  ('interpret', '解释', 'verb', 'academic', 7, 44),
  ('involve', '涉及', 'verb', 'academic', 7, 58),
  ('issue', '问题', 'noun/verb', 'academic', 7, 52),
  ('labour', '劳动', 'noun', 'academic', 7, 40),
  ('legal', '合法的', 'adjective', 'academic', 7, 45),
  ('legislate', '立法', 'verb', 'academic', 7, 35),
  ('major', '主要的', 'adjective', 'academic', 7, 50),
  ('method', '方法', 'noun', 'academic', 7, 55),
  ('occur', '发生', 'verb', 'academic', 7, 52),
  ('percent', '百分比', 'noun', 'academic', 7, 48),
  ('period', '时期', 'noun', 'academic', 7, 46),
  ('policy', '政策', 'noun', 'academic', 7, 50),
  ('principle', '原则', 'noun', 'academic', 7, 45),
  ('proceed', '继续进行', 'verb', 'academic', 7, 40),
  ('process', '过程', 'noun/verb', 'academic', 7, 62),
  ('require', '需要', 'verb', 'academic', 7, 65),
  ('respond', '回应', 'verb', 'academic', 7, 48),
  ('role', '角色', 'noun', 'academic', 7, 52),
  ('section', '部分', 'noun', 'academic', 7, 45),
  ('sector', '部门', 'noun', 'academic', 7, 42),
  ('significant', '重要的', 'adjective', 'academic', 7, 58),
  ('similar', '相似的', 'adjective', 'academic', 7, 50),
  ('source', '来源', 'noun', 'academic', 7, 48),
  ('specific', '具体的', 'adjective', 'academic', 7, 52),
  ('structure', '结构', 'noun/verb', 'academic', 7, 50),
  ('theory', '理论', 'noun', 'academic', 7, 55),
  ('vary', '变化', 'verb', 'academic', 7, 45),
  ('achieve', '实现', 'verb', 'academic', 8, 48),
  ('acquire', '获得', 'verb', 'academic', 8, 42),
  ('administrate', '管理', 'verb', 'academic', 8, 40),
  ('affect', '影响', 'verb', 'academic', 8, 55),
  ('appropriate', '适当的', 'adjective', 'academic', 8, 45),
  ('aspect', '方面', 'noun', 'academic', 8, 50),
  ('assist', '帮助', 'verb', 'academic', 8, 42),
  ('category', '类别', 'noun', 'academic', 8, 45),
  ('chapter', '章节', 'noun', 'academic', 8, 40),
  ('commission', '委员会', 'noun', 'academic', 8, 38),
  ('community', '社区', 'noun', 'academic', 8, 52),
  ('complex', '复杂的', 'adjective', 'academic', 8, 48),
  ('compute', '计算', 'verb', 'academic', 8, 35),
  ('conclude', '结论', 'verb', 'academic', 8, 44),
  ('conduct', '进行', 'verb/noun', 'academic', 8, 48),
  ('consequence', '后果', 'noun', 'academic', 8, 42),
  ('construct', '构建', 'verb', 'academic', 8, 45),
  ('consume', '消费', 'verb', 'academic', 8, 40),
  ('credit', '信用', 'noun/verb', 'academic', 8, 42),
  ('culture', '文化', 'noun', 'academic', 8, 50),
  ('design', '设计', 'verb/noun', 'academic', 8, 55),
  ('distinct', '明显的', 'adjective', 'academic', 8, 40),
  ('element', '元素', 'noun', 'academic', 8, 48),
  ('equate', '等同', 'verb', 'academic', 8, 35),
  ('evaluate', '评估', 'verb', 'academic', 8, 45),
  ('feature', '特征', 'noun', 'academic', 8, 52),
  ('final', '最终的', 'adjective', 'academic', 8, 45),
  ('focus', '焦点', 'noun/verb', 'academic', 8, 50),
  ('impact', '影响', 'noun/verb', 'academic', 8, 52),
  ('injure', '伤害', 'verb', 'academic', 8, 38),
  ('institute', '机构', 'noun', 'academic', 8, 42),
  ('invest', '投资', 'verb', 'academic', 8, 45),
  ('item', '项目', 'noun', 'academic', 8, 48),
  ('journal', '期刊', 'noun', 'academic', 8, 40),
  ('maintain', '维持', 'verb', 'academic', 8, 50),
  ('measure', '测量', 'verb/noun', 'academic', 8, 48),
  ('obtain', '获得', 'verb', 'academic', 8, 45),
  ('participate', '参与', 'verb', 'academic', 8, 42),
  ('perceive', '感知', 'verb', 'academic', 8, 38),
  ('positive', '积极的', 'adjective', 'academic', 8, 50),
  ('potential', '潜在的', 'adjective/noun', 'academic', 8, 45),
  ('previous', '以前的', 'adjective', 'academic', 8, 48),
  ('primary', '主要的', 'adjective', 'academic', 8, 45),
  ('purchase', '购买', 'verb/noun', 'academic', 8, 40),
  ('range', '范围', 'noun/verb', 'academic', 8, 52),
  ('region', '地区', 'noun', 'academic', 8, 48),
  ('regulate', '调节', 'verb', 'academic', 8, 40),
  ('relevant', '相关的', 'adjective', 'academic', 8, 45),
  ('resource', '资源', 'noun', 'academic', 8, 50),
  ('restrict', '限制', 'verb', 'academic', 8, 42),
  ('secure', '安全的', 'adjective', 'academic', 8, 40),
  ('seek', '寻找', 'verb', 'academic', 8, 45),
  ('select', '选择', 'verb', 'academic', 8, 48),
  ('site', '地点', 'noun', 'academic', 8, 45),
  ('strategy', '策略', 'noun', 'academic', 8, 42),
  ('survey', '调查', 'noun/verb', 'academic', 8, 45),
  ('text', '文本', 'noun', 'academic', 8, 52),
  ('tradition', '传统', 'noun', 'academic', 8, 40),
  ('transfer', '转移', 'verb/noun', 'academic', 8, 42),
  ('alternative', '替代的', 'adjective/noun', 'academic', 9, 45),
  ('circumstance', '环境', 'noun', 'academic', 9, 40),
  ('comment', '评论', 'noun/verb', 'academic', 9, 48),
  ('compensate', '补偿', 'verb', 'academic', 9, 35),
  ('component', '组件', 'noun', 'academic', 9, 42),
  ('consent', '同意', 'noun/verb', 'academic', 9, 38),
  ('considerable', '相当大的', 'adjective', 'academic', 9, 40),
  ('constant', '持续的', 'adjective', 'academic', 9, 42),
  ('constrain', '约束', 'verb', 'academic', 9, 35),
  ('contribute', '贡献', 'verb', 'academic', 9, 48),
  ('convene', '召集', 'verb', 'academic', 9, 30),
  ('coordinate', '协调', 'verb', 'academic', 9, 38),
  ('core', '核心', 'noun/adjective', 'academic', 9, 42),
  ('corporate', '公司的', 'adjective', 'academic', 9, 40),
  ('correspond', '对应', 'verb', 'academic', 9, 38),
  ('criteria', '标准', 'noun', 'academic', 9, 45),
  ('deduce', '推论', 'verb', 'academic', 9, 35),
  ('demonstrate', '证明', 'verb', 'academic', 9, 50),
  ('document', '文件', 'noun/verb', 'academic', 9, 48),
  ('dominate', '支配', 'verb', 'academic', 9, 40),
  ('emphasis', '强调', 'noun', 'academic', 9, 45),
  ('ensure', '确保', 'verb', 'academic', 9, 52),
  ('exclude', '排除', 'verb', 'academic', 9, 40),
  ('framework', '框架', 'noun', 'academic', 9, 42),
  ('fund', '资金', 'noun/verb', 'academic', 9, 45),
  ('illustrate', '说明', 'verb', 'academic', 9, 48),
  ('immigrate', '移民', 'verb', 'academic', 9, 35),
  ('imply', '暗示', 'verb', 'academic', 9, 45),
  ('initial', '最初的', 'adjective', 'academic', 9, 42),
  ('instance', '例子', 'noun', 'academic', 9, 45),
  ('interact', '互动', 'verb', 'academic', 9, 40),
  ('justify', '证明正当', 'verb', 'academic', 9, 38),
  ('layer', '层', 'noun', 'academic', 9, 40),
  ('link', '链接', 'noun/verb', 'academic', 9, 48),
  ('locate', '定位', 'verb', 'academic', 9, 45),
  ('maximise', '最大化', 'verb', 'academic', 9, 35),
  ('minority', '少数', 'noun', 'academic', 9, 40),
  ('negate', '否定', 'verb', 'academic', 9, 32),
  ('outcome', '结果', 'noun', 'academic', 9, 42),
  ('partner', '伙伴', 'noun', 'academic', 9, 45),
  ('philosophy', '哲学', 'noun', 'academic', 9, 38),
  ('physical', '身体的', 'adjective', 'academic', 9, 50),
  ('proportion', '比例', 'noun', 'academic', 9, 42),
  ('publish', '出版', 'verb', 'academic', 9, 50),
  ('react', '反应', 'verb', 'academic', 9, 45),
  ('register', '注册', 'verb/noun', 'academic', 9, 48),
  ('rely', '依赖', 'verb', 'academic', 9, 45),
  ('remove', '移除', 'verb', 'academic', 9, 48),
  ('scheme', '方案', 'noun', 'academic', 9, 40),
  ('sequence', '序列', 'noun', 'academic', 9, 42),
  ('sex', '性别', 'noun', 'academic', 9, 48),
  ('shift', '转移', 'verb/noun', 'academic', 9, 45),
  ('specify', '指定', 'verb', 'academic', 9, 42),
  ('sufficient', '足够的', 'adjective', 'academic', 9, 45),
  ('task', '任务', 'noun', 'academic', 9, 50),
  ('technical', '技术的', 'adjective', 'academic', 9, 48),
  ('technology', '技术', 'noun', 'academic', 9, 52),
  ('valid', '有效的', 'adjective', 'academic', 9, 40),
  ('volume', '体积', 'noun', 'academic', 9, 42),
  ('acknowledge', '承认', 'verb', 'writing', 7, 36),
  ('accommodate', '容纳', 'verb', 'reading', 7, 36),
  ('accumulate', '积累', 'verb', 'writing', 7, 36),
  ('accurate', '精确的', 'adjective', 'writing', 6, 38),
  ('adapt', '适应', 'verb', 'speaking', 6, 38),
  ('adequate', '足够的', 'adjective', 'writing', 6, 38),
  ('adjacent', '邻近的', 'adjective', 'listening', 7, 36),
  ('adjust', '调整', 'verb', 'speaking', 6, 38),
  ('advocate', '提倡', 'verb/noun', 'writing', 7, 36),
  ('allocate', '分配', 'verb', 'writing', 7, 36),
  ('alter', '改变', 'verb', 'writing', 6, 38),
  ('ambiguous', '模糊的', 'adjective', 'reading', 7, 36),
  ('anticipate', '预期', 'verb', 'speaking', 7, 36),
  ('apparent', '明显的', 'adjective', 'writing', 6, 38),
  ('append', '附加', 'verb', 'writing', 7, 36),
  ('appreciate', '欣赏', 'verb', 'speaking', 6, 38),
  ('approximate', '大约的', 'adjective', 'listening', 6, 38),
  ('arbitrary', '任意的', 'adjective', 'reading', 7, 36),
  ('articulate', '明确表达', 'verb', 'speaking', 7, 36),
  ('assert', '断言', 'verb', 'writing', 7, 36),
  ('assess', '评估', 'verb', 'writing', 6, 38),
  ('assign', '分配', 'verb', 'writing', 6, 38),
  ('attach', '附上', 'verb', 'writing', 6, 38),
  ('attain', '达到', 'verb', 'writing', 7, 36),
  ('attitude', '态度', 'noun', 'speaking', 5, 40),
  ('attribute', '归因于', 'verb/noun', 'writing', 7, 36),
  ('awareness', '意识', 'noun', 'speaking', 6, 38),
  ('abundant', '丰富的', 'adjective', 'writing', 6, 38),
  ('active', '活跃的', 'adjective', 'general', 5, 40),
  ('actual', '实际的', 'adjective', 'speaking', 5, 40),
  ('additional', '额外的', 'adjective', 'writing', 5, 40),
  ('advanced', '高级的', 'adjective', 'general', 5, 40),
  ('aesthetic', '美学的', 'adjective', 'speaking', 7, 36),
  ('affordable', '负担得起的', 'adjective', 'speaking', 6, 38),
  ('aggressive', '侵略性的', 'adjective', 'writing', 6, 38),
  ('alarming', '令人担忧的', 'adjective', 'writing', 6, 38),
  ('amazing', '令人惊奇的', 'adjective', 'speaking', 5, 40),
  ('ambitious', '有野心的', 'adjective', 'speaking', 6, 38),
  ('ancient', '古代的', 'adjective', 'reading', 5, 40),
  ('annoying', '烦人的', 'adjective', 'speaking', 5, 40),
  ('annual', '年度的', 'adjective', 'writing', 6, 38),
  ('anxious', '焦虑的', 'adjective', 'speaking', 6, 38),
  ('appalling', '可怕的', 'adjective', 'speaking', 7, 36),
  ('artificial', '人工的', 'adjective', 'reading', 6, 38),
  ('artistic', '艺术的', 'adjective', 'speaking', 6, 38),
  ('ashamed', '羞愧的', 'adjective', 'speaking', 5, 40),
  ('attractive', '有吸引力的', 'adjective', 'speaking', 5, 40),
  ('automatic', '自动的', 'adjective', 'reading', 6, 38),
  ('average', '平均的', 'adjective', 'writing', 5, 40),
  ('aware', '知道的', 'adjective', 'speaking', 5, 40),
  ('awful', '糟糕的', 'adjective', 'speaking', 5, 40),
  ('accordingly', '因此', 'adverb', 'writing', 7, 36),
  ('additionally', '此外', 'adverb', 'writing', 6, 38),
  ('afterwards', '后来', 'adverb', 'speaking', 5, 40),
  ('alternatively', '或者', 'adverb', 'writing', 6, 38),
  ('altogether', '总共', 'adverb', 'writing', 6, 38),
  ('apparently', '显然地', 'adverb', 'speaking', 6, 38),
  ('approximately', '大约', 'adverb', 'listening', 6, 38),
  ('basically', '基本上', 'adverb', 'speaking', 5, 40),
  ('besides', '此外', 'adverb', 'speaking', 5, 40),
  ('certainly', '当然', 'adverb', 'speaking', 5, 40),
  ('clearly', '清楚地', 'adverb', 'writing', 5, 40),
  ('coincidentally', '巧合地', 'adverb', 'speaking', 7, 36),
  ('collectively', '共同地', 'adverb', 'writing', 7, 36),
  ('commonly', '通常', 'adverb', 'writing', 6, 38),
  ('comparatively', '相对地', 'adverb', 'writing', 7, 36),
  ('concurrently', '同时地', 'adverb', 'writing', 7, 36),
  ('consequently', '因此', 'adverb', 'writing', 6, 38),
  ('considerably', '相当', 'adverb', 'writing', 6, 38),
  ('consistently', '一贯地', 'adverb', 'writing', 7, 36),
  ('constantly', '不断地', 'adverb', 'speaking', 6, 38),
  ('continually', '持续地', 'adverb', 'writing', 6, 38),
  ('conversely', '相反地', 'adverb', 'writing', 7, 36),
  ('currently', '目前', 'adverb', 'speaking', 5, 40),
  ('definitely', '肯定地', 'adverb', 'speaking', 5, 40),
  ('deliberately', '故意地', 'adverb', 'writing', 7, 36),
  ('dramatically', '显著地', 'adverb', 'writing', 6, 38),
  ('effectively', '有效地', 'adverb', 'writing', 6, 38),
  ('especially', '尤其', 'adverb', 'general', 5, 40),
  ('essentially', '本质上', 'adverb', 'writing', 6, 38),
  ('eventually', '最终', 'adverb', 'general', 5, 40),
  ('evidently', '明显地', 'adverb', 'writing', 7, 36),
  ('exceedingly', '极其', 'adverb', 'writing', 7, 36),
  ('exclusively', '专门地', 'adverb', 'writing', 7, 36),
  ('explicitly', '明确地', 'adverb', 'writing', 7, 36),
  ('extensively', '广泛地', 'adverb', 'writing', 7, 36),
  ('extremely', '极其', 'adverb', 'speaking', 5, 40),
  ('fundamentally', '根本上', 'adverb', 'writing', 7, 36),
  ('furthermore', '此外', 'adverb', 'writing', 6, 38),
  ('generally', '通常', 'adverb', 'general', 5, 40),
  ('gradually', '逐渐地', 'adverb', 'general', 5, 40),
  ('hopefully', '希望', 'adverb', 'speaking', 5, 40),
  ('however', '然而', 'adverb', 'general', 5, 40),
  ('immediately', '立即', 'adverb', 'general', 5, 40),
  ('increasingly', '越来越', 'adverb', 'writing', 6, 38),
  ('inevitably', '不可避免地', 'adverb', 'writing', 7, 36),
  ('initially', '最初', 'adverb', 'writing', 6, 38),
  ('instantly', '立即', 'adverb', 'speaking', 5, 40),
  ('largely', '主要地', 'adverb', 'writing', 6, 38),
  ('likely', '可能', 'adverb', 'general', 5, 40),
  ('meanwhile', '同时', 'adverb', 'writing', 5, 40),
  ('merely', '仅仅', 'adverb', 'writing', 6, 38),
  ('moderately', '适度地', 'adverb', 'writing', 6, 38),
  ('mostly', '主要地', 'adverb', 'speaking', 5, 40),
  ('namely', '即', 'adverb', 'writing', 6, 38),
  ('necessarily', '必然地', 'adverb', 'writing', 6, 38),
  ('nevertheless', '尽管如此', 'adverb', 'writing', 6, 38),
  ('normally', '通常', 'adverb', 'speaking', 5, 40),
  ('notably', '显著地', 'adverb', 'writing', 7, 36),
  ('obviously', '显然', 'adverb', 'speaking', 5, 40),
  ('occasionally', '偶尔', 'adverb', 'speaking', 5, 40),
  ('particularly', '特别', 'adverb', 'general', 5, 40),
  ('potentially', '潜在地', 'adverb', 'writing', 6, 38),
  ('presumably', '推测起来', 'adverb', 'writing', 7, 36),
  ('previously', '先前', 'adverb', 'writing', 6, 38),
  ('primarily', '主要地', 'adverb', 'writing', 6, 38),
  ('probably', '可能', 'adverb', 'speaking', 5, 40),
  ('promptly', '迅速地', 'adverb', 'writing', 6, 38),
  ('quickly', '快速地', 'adverb', 'general', 5, 40),
  ('rarely', '很少', 'adverb', 'speaking', 5, 40),
  ('readily', '容易地', 'adverb', 'writing', 6, 38),
  ('regardless', '不管', 'adverb', 'writing', 6, 38),
  ('relatively', '相对地', 'adverb', 'writing', 6, 38),
  ('remarkably', '显著地', 'adverb', 'writing', 7, 36),
  ('scarcely', '几乎不', 'adverb', 'writing', 6, 38),
  ('seldom', '很少', 'adverb', 'writing', 6, 38),
  ('seemingly', '表面上', 'adverb', 'writing', 6, 38),
  ('separately', '分别地', 'adverb', 'writing', 6, 38),
  ('significantly', '显著地', 'adverb', 'writing', 6, 38),
  ('similarly', '同样', 'adverb', 'writing', 5, 40),
  ('simultaneously', '同时地', 'adverb', 'writing', 7, 36),
  ('slightly', '稍微', 'adverb', 'speaking', 5, 40),
  ('specifically', '具体地', 'adverb', 'writing', 6, 38),
  ('steadily', '稳定地', 'adverb', 'writing', 6, 38),
  ('subsequently', '随后', 'adverb', 'writing', 6, 38),
  ('substantially', '实质上', 'adverb', 'writing', 7, 36),
  ('successfully', '成功地', 'adverb', 'writing', 6, 38),
  ('suddenly', '突然', 'adverb', 'general', 5, 40),
  ('sufficiently', '充分地', 'adverb', 'writing', 6, 38),
  ('temporarily', '暂时', 'adverb', 'writing', 6, 38),
  ('thereafter', '此后', 'adverb', 'writing', 7, 36),
  ('traditionally', '传统上', 'adverb', 'writing', 6, 38),
  ('ultimately', '最终', 'adverb', 'writing', 6, 38),
  ('undoubtedly', '无疑', 'adverb', 'writing', 6, 38),
  ('unfortunately', '不幸', 'adverb', 'speaking', 5, 40),
  ('usually', '通常', 'adverb', 'general', 5, 40),
  ('virtually', '几乎', 'adverb', 'writing', 7, 36),
  ('widely', '广泛地', 'adverb', 'writing', 6, 38),
  ('abbreviation', '缩写', 'noun', 'writing', 6, 38),
  ('ability', '能力', 'noun', 'general', 5, 40),
  ('abstract', '摘要', 'noun/adjective', 'writing', 6, 38),
  ('academy', '学院', 'noun', 'reading', 6, 38),
  ('acceptance', '接受', 'noun', 'speaking', 6, 38),
  ('access', '通道', 'noun', 'general', 5, 40),
  ('accommodation', '住宿', 'noun', 'listening', 5, 40),
  ('accomplishment', '成就', 'noun', 'speaking', 7, 36),
  ('accuracy', '准确性', 'noun', 'writing', 6, 38),
  ('achievement', '成就', 'noun', 'writing', 6, 38),
  ('acquaintance', '熟人', 'noun', 'speaking', 6, 38),
  ('acquisition', '获得', 'noun', 'reading', 7, 36),
  ('adaptation', '适应', 'noun', 'reading', 7, 36),
  ('addiction', '上瘾', 'noun', 'speaking', 6, 38),
  ('adjustment', '调整', 'noun', 'writing', 6, 38),
  ('administration', '管理', 'noun', 'writing', 6, 38),
  ('admission', '准许进入', 'noun', 'reading', 6, 38),
  ('adolescent', '青少年', 'noun/adjective', 'speaking', 7, 36),
  ('advantage', '优势', 'noun', 'general', 5, 40),
  ('adventure', '冒险', 'noun', 'speaking', 5, 40),
  ('advertisement', '广告', 'noun', 'general', 5, 40),
  ('advice', '建议', 'noun', 'speaking', 5, 40),
  ('affection', '感情', 'noun', 'speaking', 6, 38),
  ('affordability', '负担能力', 'noun', 'writing', 7, 36),
  ('agriculture', '农业', 'noun', 'reading', 6, 38),
  ('aid', '援助', 'noun', 'writing', 6, 38),
  ('allowance', '津贴', 'noun', 'listening', 6, 38),
  ('ambiguity', '歧义', 'noun', 'writing', 7, 36),
  ('ambition', '雄心', 'noun', 'speaking', 6, 38),
  ('ancestor', '祖先', 'noun', 'reading', 6, 38),
  ('anticipation', '预期', 'noun', 'writing', 7, 36),
  ('anxiety', '焦虑', 'noun', 'speaking', 6, 38),
  ('apology', '道歉', 'noun', 'speaking', 5, 40),
  ('appearance', '外观', 'noun', 'speaking', 5, 40),
  ('application', '申请', 'noun', 'general', 5, 40),
  ('appreciation', '欣赏', 'noun', 'speaking', 6, 38),
  ('approval', '批准', 'noun', 'writing', 6, 38),
  ('approximation', '近似值', 'noun', 'writing', 7, 36),
  ('archaeology', '考古学', 'noun', 'reading', 7, 36),
  ('architect', '建筑师', 'noun', 'speaking', 6, 38),
  ('architecture', '建筑', 'noun', 'speaking', 6, 38),
  ('argument', '论点', 'noun', 'writing', 5, 40),
  ('arrangement', '安排', 'noun', 'speaking', 5, 40),
  ('aspiration', '愿望', 'noun', 'speaking', 7, 36),
  ('asset', '资产', 'noun', 'reading', 7, 36),
  ('assignment', '任务', 'noun', 'writing', 6, 38),
  ('assistance', '帮助', 'noun', 'general', 6, 38),
  ('assumption', '假设', 'noun', 'writing', 6, 38),
  ('atmosphere', '气氛', 'noun', 'speaking', 6, 38),
  ('attempt', '尝试', 'noun', 'general', 5, 40),
  ('attendance', '出席', 'noun', 'writing', 6, 38),
  ('attention', '注意', 'noun', 'general', 5, 40),
  ('attraction', '吸引力', 'noun', 'speaking', 6, 38),
  ('availability', '可用性', 'noun', 'writing', 7, 36),
  ('accountant', '会计', 'noun', 'listening', 6, 38),
  ('airport', '机场', 'noun', 'listening', 5, 40),
  ('apartment', '公寓', 'noun', 'listening', 5, 40),
  ('appointment', '预约', 'noun', 'listening', 5, 40),
  ('assistant', '助手', 'noun', 'listening', 5, 40),
  ('auditorium', '礼堂', 'noun', 'listening', 7, 36),
  ('bank', '银行', 'noun', 'listening', 5, 40),
  ('bathroom', '浴室', 'noun', 'listening', 5, 40),
  ('bedroom', '卧室', 'noun', 'listening', 5, 40),
  ('bookshop', '书店', 'noun', 'listening', 5, 40),
  ('bookstore', '书店', 'noun', 'listening', 5, 40),
  ('branch', '分店', 'noun', 'listening', 6, 38),
  ('cafeteria', '自助餐厅', 'noun', 'listening', 6, 38),
  ('campus', '校园', 'noun', 'listening', 5, 40),
  ('cancellation', '取消', 'noun', 'listening', 6, 38),
  ('chemist', '药剂师', 'noun', 'listening', 6, 38),
  ('cinema', '电影院', 'noun', 'listening', 5, 40),
  ('clinic', '诊所', 'noun', 'listening', 5, 40),
  ('coffee shop', '咖啡店', 'noun', 'listening', 5, 40),
  ('college', '学院', 'noun', 'listening', 5, 40),
  ('concert', '音乐会', 'noun', 'listening', 5, 40),
  ('conference', '会议', 'noun', 'listening', 6, 38),
  ('consultation', '咨询', 'noun', 'listening', 6, 38),
  ('convenience store', '便利店', 'noun', 'listening', 5, 40),
  ('dentist', '牙医', 'noun', 'listening', 5, 40),
  ('department', '部门', 'noun', 'listening', 5, 40),
  ('deposit', '存款', 'noun', 'listening', 6, 38),
  ('dining room', '餐厅', 'noun', 'listening', 5, 40),
  ('dormitory', '宿舍', 'noun', 'listening', 5, 40),
  ('downtown', '市中心', 'noun', 'listening', 5, 40),
  ('elevator', '电梯', 'noun', 'listening', 5, 40),
  ('emergency', '紧急情况', 'noun', 'listening', 5, 40),
  ('engineer', '工程师', 'noun', 'listening', 5, 40),
  ('entrance', '入口', 'noun', 'listening', 5, 40),
  ('exhibition', '展览', 'noun', 'listening', 6, 38),
  ('facilities', '设施', 'noun', 'listening', 6, 38),
  ('faculty', '教职员', 'noun', 'listening', 6, 38),
  ('flight', '航班', 'noun', 'listening', 5, 40),
  ('garage', '车库', 'noun', 'listening', 5, 40),
  ('garden', '花园', 'noun', 'listening', 5, 40),
  ('gym', '健身房', 'noun', 'listening', 5, 40),
  ('hall', '大厅', 'noun', 'listening', 5, 40),
  ('health center', '健康中心', 'noun', 'listening', 5, 40),
  ('high school', '高中', 'noun', 'listening', 5, 40),
  ('hospital', '医院', 'noun', 'listening', 5, 40),
  ('hostel', '旅舍', 'noun', 'listening', 5, 40),
  ('hotel', '酒店', 'noun', 'listening', 5, 40),
  ('house', '房子', 'noun', 'listening', 5, 40),
  ('immigration', '移民', 'noun', 'listening', 6, 38),
  ('information desk', '咨询台', 'noun', 'listening', 5, 40),
  ('insurance', '保险', 'noun', 'listening', 5, 40),
  ('interview', '面试', 'noun', 'listening', 5, 40),
  ('journalist', '记者', 'noun', 'listening', 6, 38),
  ('kitchen', '厨房', 'noun', 'listening', 5, 40),
  ('laboratory', '实验室', 'noun', 'listening', 6, 38),
  ('lecture', '讲座', 'noun', 'listening', 5, 40),
  ('lecture hall', '阶梯教室', 'noun', 'listening', 5, 40),
  ('librarian', '图书管理员', 'noun', 'listening', 5, 40),
  ('library', '图书馆', 'noun', 'listening', 5, 40),
  ('lift', '电梯', 'noun', 'listening', 5, 40),
  ('living room', '客厅', 'noun', 'listening', 5, 40),
  ('lounge', '休息室', 'noun', 'listening', 5, 40),
  ('manager', '经理', 'noun', 'listening', 5, 40),
  ('map', '地图', 'noun', 'listening', 5, 40),
  ('market', '市场', 'noun', 'listening', 5, 40),
  ('membership', '会员资格', 'noun', 'listening', 6, 38),
  ('museum', '博物馆', 'noun', 'listening', 5, 40),
  ('nursery', '托儿所', 'noun', 'listening', 5, 40),
  ('nurse', '护士', 'noun', 'listening', 5, 40),
  ('office', '办公室', 'noun', 'listening', 5, 40),
  ('park', '公园', 'noun', 'listening', 5, 40),
  ('parking lot', '停车场', 'noun', 'listening', 5, 40),
  ('passport', '护照', 'noun', 'listening', 5, 40),
  ('pharmacy', '药店', 'noun', 'listening', 5, 40),
  ('photocopy', '复印件', 'noun', 'listening', 5, 40),
  ('post office', '邮局', 'noun', 'listening', 5, 40),
  ('professor', '教授', 'noun', 'listening', 5, 40),
  ('program', '节目', 'noun', 'listening', 5, 40),
  ('reception', '接待处', 'noun', 'listening', 5, 40),
  ('recreation', '娱乐', 'noun', 'listening', 6, 38),
  ('reference room', '资料室', 'noun', 'listening', 5, 40),
  ('refund', '退款', 'noun', 'listening', 6, 38),
  ('rehearsal', '排练', 'noun', 'listening', 7, 36),
  ('rent', '租金', 'noun', 'listening', 5, 40),
  ('repair', '修理', 'noun', 'listening', 5, 40),
  ('reporter', '记者', 'noun', 'listening', 5, 40),
  ('reservation', '预订', 'noun', 'listening', 5, 40),
  ('residence', '住宅', 'noun', 'listening', 6, 38),
  ('resort', '度假胜地', 'noun', 'listening', 6, 38),
  ('restaurant', '餐厅', 'noun', 'listening', 5, 40),
  ('roommate', '室友', 'noun', 'listening', 5, 40),
  ('route', '路线', 'noun', 'listening', 5, 40),
  ('school', '学校', 'noun', 'listening', 5, 40),
  ('semester', '学期', 'noun', 'listening', 5, 40),
  ('seminar', '研讨会', 'noun', 'listening', 6, 38),
  ('service', '服务', 'noun', 'listening', 5, 40),
  ('shop', '商店', 'noun', 'listening', 5, 40),
  ('shopping center', '购物中心', 'noun', 'listening', 5, 40),
  ('souvenir', '纪念品', 'noun', 'listening', 5, 40),
  ('specialist', '专家', 'noun', 'listening', 6, 38),
  ('stadium', '体育场', 'noun', 'listening', 5, 40),
  ('station', '车站', 'noun', 'listening', 5, 40),
  ('student', '学生', 'noun', 'listening', 5, 40),
  ('studio', '工作室', 'noun', 'listening', 5, 40),
  ('study', '书房', 'noun', 'listening', 5, 40),
  ('supermarket', '超市', 'noun', 'listening', 5, 40),
  ('surgery', '外科手术', 'noun', 'listening', 6, 38),
  ('symposium', '座谈会', 'noun', 'listening', 7, 36),
  ('teacher', '教师', 'noun', 'listening', 5, 40),
  ('terminal', '终点站', 'noun', 'listening', 6, 38),
  ('theater', '剧院', 'noun', 'listening', 5, 40),
  ('theatre', '剧院', 'noun', 'listening', 5, 40),
  ('ticket', '票', 'noun', 'listening', 5, 40),
  ('tour', '旅行', 'noun', 'listening', 5, 40),
  ('tourist', '游客', 'noun', 'listening', 5, 40),
  ('towel', '毛巾', 'noun', 'listening', 5, 40),
  ('traffic', '交通', 'noun', 'listening', 5, 40),
  ('travel', '旅行', 'noun', 'listening', 5, 40),
  ('tutor', '导师', 'noun', 'listening', 5, 40),
  ('university', '大学', 'noun', 'listening', 5, 40),
  ('vacation', '假期', 'noun', 'listening', 5, 40),
  ('visa', '签证', 'noun', 'listening', 5, 40),
  ('waiting room', '候诊室', 'noun', 'listening', 5, 40),
  ('workshop', '研讨会', 'noun', 'listening', 6, 38),
  ('youth hostel', '青年旅社', 'noun', 'listening', 5, 40),
  ('account for', '解释，占', 'phrasal verb', 'phrase', 6, 45),
  ('adapt to', '适应', 'phrasal verb', 'phrase', 6, 45),
  ('aim at', '旨在', 'phrasal verb', 'phrase', 6, 45),
  ('allow for', '考虑到', 'phrasal verb', 'phrase', 6, 45),
  ('apply for', '申请', 'phrasal verb', 'phrase', 5, 45),
  ('associate with', '与...有关', 'phrasal verb', 'phrase', 6, 45),
  ('base on', '基于', 'phrasal verb', 'phrase', 6, 45),
  ('belong to', '属于', 'phrasal verb', 'phrase', 5, 45),
  ('benefit from', '受益于', 'phrasal verb', 'phrase', 6, 45),
  ('call for', '需要', 'phrasal verb', 'phrase', 6, 45),
  ('care for', '关心', 'phrasal verb', 'phrase', 5, 45),
  ('cater for', '迎合', 'phrasal verb', 'phrase', 6, 45),
  ('check in', '登记入住', 'phrasal verb', 'phrase', 5, 45),
  ('check out', '结账离开', 'phrasal verb', 'phrase', 5, 45),
  ('comply with', '遵守', 'phrasal verb', 'phrase', 6, 45),
  ('consist of', '由...组成', 'phrasal verb', 'phrase', 6, 45),
  ('cope with', '应对', 'phrasal verb', 'phrase', 6, 45),
  ('count on', '指望', 'phrasal verb', 'phrase', 5, 45),
  ('cut down on', '削减', 'phrasal verb', 'phrase', 6, 45),
  ('deal with', '处理', 'phrasal verb', 'phrase', 5, 45),
  ('depend on', '依赖', 'phrasal verb', 'phrase', 5, 45),
  ('derive from', '源自', 'phrasal verb', 'phrase', 7, 45),
  ('devote to', '致力于', 'phrasal verb', 'phrase', 6, 45),
  ('dispose of', '处理', 'phrasal verb', 'phrase', 6, 45),
  ('draw on', '利用', 'phrasal verb', 'phrase', 6, 45),
  ('dwell on', '详述', 'phrasal verb', 'phrase', 7, 45),
  ('engage in', '从事', 'phrasal verb', 'phrase', 6, 45),
  ('equip with', '配备', 'phrasal verb', 'phrase', 6, 45),
  ('fall behind', '落后', 'phrasal verb', 'phrase', 5, 45),
  ('figure out', '弄明白', 'phrasal verb', 'phrase', 5, 45),
  ('fill in', '填写', 'phrasal verb', 'phrase', 5, 45),
  ('fill out', '填写', 'phrasal verb', 'phrase', 5, 45),
  ('focus on', '集中于', 'phrasal verb', 'phrase', 6, 45),
  ('get along with', '相处', 'phrasal verb', 'phrase', 5, 45),
  ('get rid of', '摆脱', 'phrasal verb', 'phrase', 5, 45),
  ('give up', '放弃', 'phrasal verb', 'phrase', 5, 45),
  ('go over', '复习', 'phrasal verb', 'phrase', 5, 45),
  ('happen to', '碰巧', 'phrasal verb', 'phrase', 5, 45),
  ('head for', '前往', 'phrasal verb', 'phrase', 5, 45),
  ('hear from', '收到...来信', 'phrasal verb', 'phrase', 5, 45),
  ('insist on', '坚持', 'phrasal verb', 'phrase', 6, 45),
  ('interact with', '互动', 'phrasal verb', 'phrase', 6, 45),
  ('invest in', '投资', 'phrasal verb', 'phrase', 6, 45),
  ('keep up with', '跟上', 'phrasal verb', 'phrase', 5, 45),
  ('lay off', '解雇', 'phrasal verb', 'phrase', 6, 45),
  ('lead to', '导致', 'phrasal verb', 'phrase', 6, 45),
  ('leave out', '省略', 'phrasal verb', 'phrase', 6, 45),
  ('lie in', '在于', 'phrasal verb', 'phrase', 7, 45),
  ('live on', '靠...生活', 'phrasal verb', 'phrase', 5, 45),
  ('look after', '照顾', 'phrasal verb', 'phrase', 5, 45),
  ('look forward to', '期待', 'phrasal verb', 'phrase', 5, 45),
  ('look into', '调查', 'phrasal verb', 'phrase', 6, 45),
  ('make out', '辨认出', 'phrasal verb', 'phrase', 5, 45),
  ('make up', '组成，编造', 'phrasal verb', 'phrase', 5, 45),
  ('object to', '反对', 'phrasal verb', 'phrase', 6, 45),
  ('participate in', '参与', 'phrasal verb', 'phrase', 6, 45),
  ('pay for', '支付', 'phrasal verb', 'phrase', 5, 45),
  ('pick up', '捡起，学会', 'phrasal verb', 'phrase', 5, 45),
  ('point out', '指出', 'phrasal verb', 'phrase', 6, 45),
  ('prepare for', '准备', 'phrasal verb', 'phrase', 5, 45),
  ('prevent from', '阻止', 'phrasal verb', 'phrase', 6, 45),
  ('prohibit from', '禁止', 'phrasal verb', 'phrase', 7, 45),
  ('pull up', '停下', 'phrasal verb', 'phrase', 5, 45),
  ('put away', '收起来', 'phrasal verb', 'phrase', 5, 45),
  ('put off', '推迟', 'phrasal verb', 'phrase', 5, 45),
  ('put on', '穿上', 'phrasal verb', 'phrase', 5, 45),
  ('put up with', '忍受', 'phrasal verb', 'phrase', 6, 45),
  ('refer to', '参考，指的是', 'phrasal verb', 'phrase', 6, 45),
  ('rely on', '依赖', 'phrasal verb', 'phrase', 6, 45),
  ('result in', '导致', 'phrasal verb', 'phrase', 6, 45),
  ('run out of', '用完', 'phrasal verb', 'phrase', 5, 45),
  ('set off', '出发', 'phrasal verb', 'phrase', 5, 45),
  ('set out', '出发，开始', 'phrasal verb', 'phrase', 6, 45),
  ('set up', '建立', 'phrasal verb', 'phrase', 6, 45),
  ('settle down', '定居', 'phrasal verb', 'phrase', 5, 45),
  ('show up', '出现', 'phrasal verb', 'phrase', 5, 45),
  ('shut down', '关闭', 'phrasal verb', 'phrase', 6, 45),
  ('slow down', '减速', 'phrasal verb', 'phrase', 5, 45),
  ('sort out', '解决', 'phrasal verb', 'phrase', 5, 45),
  ('speak up', '大声说', 'phrasal verb', 'phrase', 5, 45),
  ('speak out', '大声说', 'phrasal verb', 'phrase', 6, 45),
  ('speed up', '加速', 'phrasal verb', 'phrase', 6, 45),
  ('stand for', '代表', 'phrasal verb', 'phrase', 6, 45),
  ('stand out', '突出', 'phrasal verb', 'phrase', 6, 45),
  ('start up', '启动', 'phrasal verb', 'phrase', 6, 45),
  ('stick to', '坚持', 'phrasal verb', 'phrase', 5, 45),
  ('subscribe to', '订阅', 'phrasal verb', 'phrase', 6, 45),
  ('suffer from', '遭受', 'phrasal verb', 'phrase', 6, 45),
  ('switch off', '关掉', 'phrasal verb', 'phrase', 5, 45),
  ('switch on', '打开', 'phrasal verb', 'phrase', 5, 45),
  ('take after', '像', 'phrasal verb', 'phrase', 5, 45),
  ('take away', '拿走', 'phrasal verb', 'phrase', 5, 45),
  ('take care of', '照顾', 'phrasal verb', 'phrase', 5, 45),
  ('take off', '起飞', 'phrasal verb', 'phrase', 5, 45),
  ('take on', '承担', 'phrasal verb', 'phrase', 6, 45),
  ('take over', '接管', 'phrasal verb', 'phrase', 6, 45),
  ('take up', '开始从事', 'phrasal verb', 'phrase', 6, 45),
  ('talk over', '讨论', 'phrasal verb', 'phrase', 5, 45),
  ('tell off', '责备', 'phrasal verb', 'phrase', 5, 45),
  ('think over', '仔细考虑', 'phrasal verb', 'phrase', 5, 45),
  ('throw away', '扔掉', 'phrasal verb', 'phrase', 5, 45),
  ('translate into', '翻译成', 'phrasal verb', 'phrase', 6, 45),
  ('try on', '试穿', 'phrasal verb', 'phrase', 5, 45),
  ('try out', '试用', 'phrasal verb', 'phrase', 5, 45),
  ('turn down', '拒绝，调小', 'phrasal verb', 'phrase', 5, 45),
  ('turn into', '变成', 'phrasal verb', 'phrase', 6, 45),
  ('turn off', '关掉', 'phrasal verb', 'phrase', 5, 45),
  ('turn on', '打开', 'phrasal verb', 'phrase', 5, 45),
  ('turn out', '结果是', 'phrasal verb', 'phrase', 6, 45),
  ('turn up', '出现，调大', 'phrasal verb', 'phrase', 5, 45),
  ('use up', '用完', 'phrasal verb', 'phrase', 5, 45),
  ('wake up', '醒来', 'phrasal verb', 'phrase', 5, 45),
  ('warm up', '热身', 'phrasal verb', 'phrase', 5, 45),
  ('watch out', '小心', 'phrasal verb', 'phrase', 5, 45),
  ('work on', '从事', 'phrasal verb', 'phrase', 5, 45),
  ('work out', '解决，锻炼', 'phrasal verb', 'phrase', 5, 45),
  ('write down', '写下', 'phrasal verb', 'phrase', 5, 45),
  ('according to', '根据', 'prepositional phrase', 'phrase', 5, 45),
  ('apart from', '除了', 'prepositional phrase', 'phrase', 6, 45),
  ('as a result', '结果', 'prepositional phrase', 'phrase', 5, 45),
  ('as far as', '至于', 'prepositional phrase', 'phrase', 5, 45),
  ('as for', '至于', 'prepositional phrase', 'phrase', 5, 45),
  ('as long as', '只要', 'prepositional phrase', 'phrase', 5, 45),
  ('as soon as', '一...就', 'prepositional phrase', 'phrase', 5, 45),
  ('as well as', '也', 'prepositional phrase', 'phrase', 5, 45),
  ('at least', '至少', 'prepositional phrase', 'phrase', 5, 45),
  ('at most', '至多', 'prepositional phrase', 'phrase', 5, 45),
  ('because of', '因为', 'prepositional phrase', 'phrase', 5, 45),
  ('by means of', '通过', 'prepositional phrase', 'phrase', 6, 45),
  ('due to', '由于', 'prepositional phrase', 'phrase', 6, 45),
  ('except for', '除了', 'prepositional phrase', 'phrase', 6, 45),
  ('in accordance with', '按照', 'prepositional phrase', 'phrase', 7, 45),
  ('in addition to', '除了', 'prepositional phrase', 'phrase', 6, 45),
  ('in case of', '万一', 'prepositional phrase', 'phrase', 5, 45),
  ('in charge of', '负责', 'prepositional phrase', 'phrase', 5, 45),
  ('in comparison with', '与...相比', 'prepositional phrase', 'phrase', 6, 45),
  ('in contrast to', '与...对比', 'prepositional phrase', 'phrase', 6, 45),
  ('in favor of', '支持', 'prepositional phrase', 'phrase', 6, 45),
  ('in front of', '在...前面', 'prepositional phrase', 'phrase', 5, 45),
  ('in terms of', '就...而言', 'prepositional phrase', 'phrase', 6, 45),
  ('in spite of', '尽管', 'prepositional phrase', 'phrase', 6, 45),
  ('instead of', '代替', 'prepositional phrase', 'phrase', 5, 45),
  ('on account of', '因为', 'prepositional phrase', 'phrase', 7, 45),
  ('on behalf of', '代表', 'prepositional phrase', 'phrase', 7, 45),
  ('on the contrary', '相反', 'prepositional phrase', 'phrase', 6, 45),
  ('prior to', '在...之前', 'prepositional phrase', 'phrase', 7, 45),
  ('regardless of', '不管', 'prepositional phrase', 'phrase', 6, 45),
  ('thanks to', '多亏', 'prepositional phrase', 'phrase', 5, 45),
  ('with regard to', '关于', 'prepositional phrase', 'phrase', 6, 45),
  ('with respect to', '关于', 'prepositional phrase', 'phrase', 7, 45),
  ('a great deal of', '大量的', 'fixed phrase', 'phrase', 5, 45),
  ('a large number of', '大量的', 'fixed phrase', 'phrase', 5, 45),
  ('a wide range of', '广泛的', 'fixed phrase', 'phrase', 6, 45),
  ('at the same time', '同时', 'fixed phrase', 'phrase', 5, 45),
  ('for example', '例如', 'fixed phrase', 'phrase', 5, 45),
  ('for instance', '例如', 'fixed phrase', 'phrase', 5, 45),
  ('in conclusion', '总之', 'fixed phrase', 'phrase', 6, 45),
  ('in fact', '事实上', 'fixed phrase', 'phrase', 5, 45),
  ('in general', '一般来说', 'fixed phrase', 'phrase', 5, 45),
  ('in order to', '为了', 'fixed phrase', 'phrase', 5, 45),
  ('in other words', '换句话说', 'fixed phrase', 'phrase', 5, 45),
  ('in particular', '尤其', 'fixed phrase', 'phrase', 6, 45),
  ('in short', '简言之', 'fixed phrase', 'phrase', 6, 45),
  ('more and more', '越来越多', 'fixed phrase', 'phrase', 5, 45),
  ('more or less', '或多或少', 'fixed phrase', 'phrase', 5, 45),
  ('no longer', '不再', 'fixed phrase', 'phrase', 5, 45),
  ('not only...but also', '不仅...而且', 'fixed phrase', 'phrase', 5, 45),
  ('on average', '平均', 'fixed phrase', 'phrase', 6, 45),
  ('on the other hand', '另一方面', 'fixed phrase', 'phrase', 5, 45),
  ('so far', '到目前为止', 'fixed phrase', 'phrase', 5, 45),
  ('such as', '例如', 'fixed phrase', 'phrase', 5, 45),
  ('to some extent', '在某种程度上', 'fixed phrase', 'phrase', 6, 45),
  ('able', '能够', 'adjective', 'core', 5, 45),
  ('about', '关于', 'preposition', 'core', 4, 50),
  ('above', '在...之上', 'preposition', 'core', 4, 50),
  ('accept', '接受', 'verb', 'core', 5, 45),
  ('accident', '事故', 'noun', 'core', 5, 45),
  ('according', '根据', 'preposition', 'core', 5, 45),
  ('account', '账户', 'noun', 'core', 5, 45),
  ('across', '穿过', 'preposition', 'core', 4, 50),
  ('act', '行动', 'verb', 'core', 5, 45),
  ('action', '行动', 'noun', 'core', 5, 45),
  ('activity', '活动', 'noun', 'core', 5, 45),
  ('actor', '演员', 'noun', 'core', 5, 45),
  ('actually', '实际上', 'adverb', 'core', 5, 45),
  ('add', '添加', 'verb', 'core', 4, 50),
  ('addition', '添加', 'noun', 'core', 5, 45),
  ('address', '地址', 'noun', 'core', 5, 45),
  ('admit', '承认', 'verb', 'core', 5, 45),
  ('adult', '成人', 'noun', 'core', 5, 45),
  ('advance', '前进', 'noun/verb', 'core', 5, 45),
  ('advertising', '广告', 'noun', 'core', 5, 45),
  ('afford', '负担得起', 'verb', 'core', 5, 45),
  ('afraid', '害怕的', 'adjective', 'core', 4, 50),
  ('after', '在...之后', 'preposition', 'core', 4, 50),
  ('afternoon', '下午', 'noun', 'core', 4, 50),
  ('again', '再次', 'adverb', 'core', 4, 50),
  ('against', '反对', 'preposition', 'core', 5, 45),
  ('age', '年龄', 'noun', 'core', 4, 50),
  ('agency', '代理', 'noun', 'core', 6, 40),
  ('agent', '代理人', 'noun', 'core', 5, 45),
  ('ago', '以前', 'adverb', 'core', 4, 50),
  ('agree', '同意', 'verb', 'core', 4, 50),
  ('agreement', '协议', 'noun', 'core', 5, 45),
  ('ahead', '向前', 'adverb', 'core', 5, 45),
  ('air', '空气', 'noun', 'core', 4, 50),
  ('aircraft', '飞机', 'noun', 'core', 5, 45),
  ('airline', '航空公司', 'noun', 'core', 5, 45),
  ('alarm', '警报', 'noun', 'core', 5, 45),
  ('alive', '活着的', 'adjective', 'core', 5, 45),
  ('all', '所有', 'determiner', 'core', 4, 50),
  ('allow', '允许', 'verb', 'core', 5, 45),
  ('almost', '几乎', 'adverb', 'core', 5, 45),
  ('alone', '独自', 'adjective/adverb', 'core', 5, 45),
  ('along', '沿着', 'preposition', 'core', 4, 50),
  ('already', '已经', 'adverb', 'core', 5, 45),
  ('also', '也', 'adverb', 'core', 4, 50),
  ('although', '虽然', 'conjunction', 'core', 5, 45),
  ('always', '总是', 'adverb', 'core', 4, 50),
  ('amaze', '使惊奇', 'verb', 'core', 5, 45),
  ('amount', '数量', 'noun', 'core', 5, 45),
  ('analyse', '分析', 'verb', 'core', 6, 40),
  ('and', '和', 'conjunction', 'core', 4, 50),
  ('anger', '愤怒', 'noun', 'core', 5, 45),
  ('angle', '角度', 'noun', 'core', 5, 45),
  ('angry', '生气的', 'adjective', 'core', 4, 50),
  ('animal', '动物', 'noun', 'core', 4, 50),
  ('announce', '宣布', 'verb', 'core', 5, 45),
  ('another', '另一个', 'determiner', 'core', 4, 50),
  ('answer', '答案', 'noun', 'core', 4, 50),
  ('any', '任何', 'determiner', 'core', 4, 50),
  ('anybody', '任何人', 'pronoun', 'core', 4, 50),
  ('anyone', '任何人', 'pronoun', 'core', 4, 50),
  ('anything', '任何事', 'pronoun', 'core', 4, 50),
  ('anyway', '无论如何', 'adverb', 'core', 5, 45),
  ('anywhere', '任何地方', 'adverb', 'core', 4, 50),
  ('apart', '分开', 'adverb', 'core', 5, 45),
  ('appeal', '呼吁', 'noun/verb', 'core', 5, 45),
  ('appear', '出现', 'verb', 'core', 4, 50),
  ('apply', '申请', 'verb', 'core', 5, 45),
  ('appoint', '任命', 'verb', 'core', 6, 40),
  ('approve', '批准', 'verb', 'core', 5, 45),
  ('argue', '争论', 'verb', 'core', 5, 45),
  ('arise', '出现', 'verb', 'core', 6, 40),
  ('arm', '手臂', 'noun', 'core', 4, 50),
  ('armed', '武装的', 'adjective', 'core', 5, 45),
  ('army', '军队', 'noun', 'core', 5, 45),
  ('around', '周围', 'adverb/preposition', 'core', 4, 50),
  ('arrange', '安排', 'verb', 'core', 5, 45),
  ('arrest', '逮捕', 'verb/noun', 'core', 5, 45),
  ('arrival', '到达', 'noun', 'core', 5, 45),
  ('arrive', '到达', 'verb', 'core', 4, 50),
  ('art', '艺术', 'noun', 'core', 4, 50),
  ('article', '文章', 'noun', 'core', 5, 45),
  ('artist', '艺术家', 'noun', 'core', 5, 45),
  ('as', '作为', 'preposition', 'core', 4, 50),
  ('aside', '在旁边', 'adverb', 'core', 5, 45),
  ('ask', '问', 'verb', 'core', 4, 50),
  ('asleep', '睡着的', 'adjective', 'core', 4, 50),
  ('associate', '联系', 'verb', 'core', 5, 45),
  ('association', '协会', 'noun', 'core', 5, 45),
  ('attack', '攻击', 'verb/noun', 'core', 5, 45),
  ('attend', '参加', 'verb', 'core', 5, 45),
  ('attract', '吸引', 'verb', 'core', 5, 45),
  ('audience', '观众', 'noun', 'core', 5, 45),
  ('author', '作者', 'noun', 'core', 5, 45),
  ('avoid', '避免', 'verb', 'core', 5, 45),
  ('award', '奖励', 'noun/verb', 'core', 5, 45),
  ('away', '离开', 'adverb', 'core', 4, 50),
  ('baby', '婴儿', 'noun', 'core', 4, 50),
  ('back', '后面', 'noun/adverb', 'core', 4, 50),
  ('background', '背景', 'noun', 'core', 5, 45),
  ('backwards', '向后', 'adverb', 'core', 5, 45),
  ('bacteria', '细菌', 'noun', 'core', 6, 40),
  ('bad', '坏的', 'adjective', 'core', 4, 50),
  ('bag', '包', 'noun', 'core', 4, 50),
  ('bake', '烘烤', 'verb', 'core', 5, 45),
  ('balance', '平衡', 'noun/verb', 'core', 5, 45),
  ('ball', '球', 'noun', 'core', 4, 50),
  ('ban', '禁止', 'verb/noun', 'core', 5, 45),
  ('band', '乐队', 'noun', 'core', 5, 45),
  ('bar', '酒吧', 'noun', 'core', 4, 50),
  ('barrier', '障碍', 'noun', 'core', 6, 40),
  ('base', '基础', 'noun/verb', 'core', 5, 45),
  ('based', '基于', 'adjective', 'core', 5, 45),
  ('basic', '基本的', 'adjective', 'core', 5, 45),
  ('basis', '基础', 'noun', 'core', 5, 45),
  ('basket', '篮子', 'noun', 'core', 4, 50),
  ('bath', '洗澡', 'noun', 'core', 4, 50),
  ('battery', '电池', 'noun', 'core', 5, 45),
  ('battle', '战斗', 'noun', 'core', 5, 45),
  ('beach', '海滩', 'noun', 'core', 4, 50),
  ('bean', '豆子', 'noun', 'core', 4, 50),
  ('bear', '熊', 'noun', 'core', 4, 50),
  ('beat', '打败', 'verb', 'core', 5, 45),
  ('beautiful', '美丽的', 'adjective', 'core', 4, 50),
  ('beauty', '美丽', 'noun', 'core', 5, 45),
  ('because', '因为', 'conjunction', 'core', 4, 50),
  ('become', '成为', 'verb', 'core', 4, 50),
  ('bed', '床', 'noun', 'core', 4, 50),
  ('beef', '牛肉', 'noun', 'core', 4, 50),
  ('beer', '啤酒', 'noun', 'core', 4, 50),
  ('before', '在...之前', 'preposition', 'core', 4, 50),
  ('begin', '开始', 'verb', 'core', 4, 50),
  ('beginning', '开始', 'noun', 'core', 4, 50),
  ('behaviour', '行为', 'noun', 'core', 5, 45),
  ('behind', '在...后面', 'preposition', 'core', 4, 50),
  ('being', '存在', 'noun', 'core', 5, 45),
  ('belief', '信仰', 'noun', 'core', 5, 45),
  ('believe', '相信', 'verb', 'core', 4, 50),
  ('bell', '铃', 'noun', 'core', 4, 50),
  ('belong', '属于', 'verb', 'core', 5, 45),
  ('below', '在...下面', 'preposition', 'core', 4, 50),
  ('belt', '腰带', 'noun', 'core', 5, 45),
  ('beneath', '在...下方', 'preposition', 'core', 6, 40),
  ('best', '最好的', 'adjective', 'core', 4, 50),
  ('better', '更好的', 'adjective', 'core', 4, 50),
  ('between', '在...之间', 'preposition', 'core', 4, 50),
  ('beyond', '超过', 'preposition', 'core', 5, 45),
  ('bicycle', '自行车', 'noun', 'core', 4, 50),
  ('big', '大的', 'adjective', 'core', 4, 50),
  ('bike', '自行车', 'noun', 'core', 4, 50),
  ('bill', '账单', 'noun', 'core', 5, 45),
  ('billion', '十亿', 'number', 'core', 5, 45),
  ('bin', '垃圾箱', 'noun', 'core', 4, 50),
  ('biology', '生物学', 'noun', 'core', 5, 45),
  ('bird', '鸟', 'noun', 'core', 4, 50),
  ('birth', '出生', 'noun', 'core', 5, 45),
  ('birthday', '生日', 'noun', 'core', 4, 50),
  ('biscuit', '饼干', 'noun', 'core', 4, 50),
  ('bit', '一点', 'noun', 'core', 4, 50),
  ('bite', '咬', 'verb', 'core', 4, 50),
  ('bitter', '苦的', 'adjective', 'core', 5, 45),
  ('black', '黑色的', 'adjective', 'core', 4, 50),
  ('blame', '责备', 'verb', 'core', 5, 45),
  ('blind', '盲的', 'adjective', 'core', 5, 45),
  ('block', '街区', 'noun', 'core', 5, 45),
  ('blog', '博客', 'noun', 'core', 5, 45),
  ('blonde', '金发的', 'adjective', 'core', 5, 45),
  ('blood', '血', 'noun', 'core', 4, 50),
  ('blow', '吹', 'verb', 'core', 4, 50),
  ('blue', '蓝色的', 'adjective', 'core', 4, 50),
  ('board', '板', 'noun', 'core', 4, 50),
  ('boat', '船', 'noun', 'core', 4, 50),
  ('body', '身体', 'noun', 'core', 4, 50),
  ('boil', '沸腾', 'verb', 'core', 5, 45),
  ('bomb', '炸弹', 'noun', 'core', 5, 45),
  ('bone', '骨头', 'noun', 'core', 4, 50),
  ('book', '书', 'noun', 'core', 4, 50),
  ('border', '边界', 'noun', 'core', 5, 45),
  ('bored', '无聊的', 'adjective', 'core', 4, 50),
  ('boring', '无聊的', 'adjective', 'core', 4, 50),
  ('born', '出生', 'adjective', 'core', 4, 50),
  ('borrow', '借', 'verb', 'core', 4, 50),
  ('boss', '老板', 'noun', 'core', 5, 45),
  ('both', '两者都', 'determiner', 'core', 4, 50),
  ('bother', '打扰', 'verb', 'core', 5, 45),
  ('bottle', '瓶子', 'noun', 'core', 4, 50),
  ('bottom', '底部', 'noun', 'core', 4, 50),
  ('bowl', '碗', 'noun', 'core', 4, 50),
  ('box', '盒子', 'noun', 'core', 4, 50),
  ('boy', '男孩', 'noun', 'core', 4, 50),
  ('brain', '大脑', 'noun', 'core', 5, 45),
  ('brand', '品牌', 'noun', 'core', 5, 45),
  ('brave', '勇敢的', 'adjective', 'core', 5, 45),
  ('bread', '面包', 'noun', 'core', 4, 50),
  ('break', '打破', 'verb', 'core', 4, 50),
  ('breakfast', '早餐', 'noun', 'core', 4, 50),
  ('breast', '胸部', 'noun', 'core', 5, 45),
  ('breath', '呼吸', 'noun', 'core', 5, 45),
  ('breathe', '呼吸', 'verb', 'core', 5, 45),
  ('brick', '砖', 'noun', 'core', 5, 45),
  ('bridge', '桥', 'noun', 'core', 4, 50),
  ('brief', '简短的', 'adjective', 'core', 5, 45),
  ('bright', '明亮的', 'adjective', 'core', 4, 50),
  ('brilliant', '杰出的', 'adjective', 'core', 5, 45),
  ('bring', '带来', 'verb', 'core', 4, 50),
  ('broad', '宽的', 'adjective', 'core', 5, 45),
  ('broadcast', '广播', 'verb/noun', 'core', 5, 45),
  ('brother', '兄弟', 'noun', 'core', 4, 50),
  ('brown', '棕色的', 'adjective', 'core', 4, 50),
  ('brush', '刷子', 'noun', 'core', 4, 50),
  ('budget', '预算', 'noun', 'core', 6, 40),
  ('build', '建造', 'verb', 'core', 4, 50),
  ('building', '建筑物', 'noun', 'core', 4, 50),
  ('bullet', '子弹', 'noun', 'core', 5, 45),
  ('bunch', '一束', 'noun', 'core', 5, 45),
  ('burn', '燃烧', 'verb', 'core', 4, 50),
  ('bury', '埋葬', 'verb', 'core', 5, 45),
  ('bus', '公共汽车', 'noun', 'core', 4, 50),
  ('business', '生意', 'noun', 'core', 5, 45),
  ('busy', '忙碌的', 'adjective', 'core', 4, 50),
  ('but', '但是', 'conjunction', 'core', 4, 50),
  ('butter', '黄油', 'noun', 'core', 4, 50),
  ('button', '按钮', 'noun', 'core', 4, 50),
  ('buy', '买', 'verb', 'core', 4, 50),
  ('by', '通过', 'preposition', 'core', 4, 50);