import { staticAssetUrl } from '../../../../lib/staticAssetUrl'

const assetPath = (path: string) => staticAssetUrl(path)

export const gameAsset = {
  map: {
    large: assetPath('/game/map_large.png'),
    small: assetPath('/game/map_small.png'),
    backgrounds: {
      desktop: assetPath('/game/map_background_desktop.png'),
      tablet: assetPath('/game/map_background_tablet.png'),
      mobile: assetPath('/game/map_background_mobile.png'),
    },
    layers: {
      far: assetPath('/game/map_layer_far.png'),
      mid: assetPath('/game/map_layer_mid.png'),
      front: assetPath('/game/map_layer_front.png'),
    },
    forest: assetPath('/game/map_forest.png'),
    lake: assetPath('/game/map_lake.png'),
    mountain: assetPath('/game/map_mountain.png'),
    castle: assetPath('/game/map_castle.png'),
    completed: assetPath('/game/map_completed.png'),
    locked: assetPath('/game/map_locked.png'),
    nodes: [
      assetPath('/game/map_node1.png'),
      assetPath('/game/map_node2.png'),
      assetPath('/game/map_node3.png'),
      assetPath('/game/map_node4.png'),
      assetPath('/game/map_node5.png'),
    ],
  },
  levels: {
    spelling: assetPath('/game/level_card_spell.png'),
    pronunciation: assetPath('/game/level_card_pronunciation.png'),
    definition: assetPath('/game/level_card_definition.png'),
    speaking: assetPath('/game/level_card_speaking.png'),
    example: assetPath('/game/level_card_example.png'),
  },
  scenes: {
    spelling: assetPath('/game/scene_spell.png'),
    pronunciation: assetPath('/game/scene_pronunciation.png'),
    definition: assetPath('/game/scene_definition.png'),
    speaking: assetPath('/game/scene_speaking.png'),
    example: assetPath('/game/scene_example.png'),
  },
  icons: {
    spelling: assetPath('/game/icon_spelling.png'),
    pronunciation: assetPath('/game/icon_pronunciation.png'),
    definition: assetPath('/game/icon_definition.png'),
    speaking: assetPath('/game/icon_speaking.png'),
    example: assetPath('/game/icon_example.png'),
    play: assetPath('/game/icon_play.png'),
    pause: assetPath('/game/icon_pause.png'),
    soundOn: assetPath('/game/icon_sound_on.png'),
    home: assetPath('/game/icon_home.png'),
    restart: assetPath('/game/icon_restart.png'),
    current: assetPath('/game/icon_current.png'),
    notebook: assetPath('/game/icon_notebook.png'),
    reward: assetPath('/game/icon_reward.png'),
    target: assetPath('/game/icon_target.png'),
    settings: assetPath('/game/icon_settings.png'),
    shop: assetPath('/game/icon_shop.png'),
  },
  character: {
    boyIdle: assetPath('/game/hero_boy_idle.png'),
    boyRun: assetPath('/game/hero_boy_run.png'),
    boyCheer: assetPath('/game/hero_boy_cheer.png'),
    girlStand: assetPath('/game/hero_girl_stand.png'),
    teacher: assetPath('/game/bird_teacher_point_book.png'),
    robot: assetPath('/game/robot_wave.png'),
  },
  reward: {
    coin: assetPath('/game/coin.png'),
    diamond: assetPath('/game/diamond.png'),
    exp: assetPath('/game/exp.png'),
    energy: assetPath('/game/energy.png'),
    heart: assetPath('/game/heart.png'),
    chestNormal: assetPath('/game/chest_normal.png'),
    chestSapphire: assetPath('/game/chest_sapphire.png'),
    chestGolden: assetPath('/game/chest_golden.png'),
    chestSpecial: assetPath('/game/chest_special.png'),
    star1: assetPath('/game/star1.png'),
    star2: assetPath('/game/star2.png'),
    star3: assetPath('/game/star3.png'),
    starGrey1: assetPath('/game/star_grey1.png'),
    starGrey2: assetPath('/game/star_grey2.png'),
    starGrey3: assetPath('/game/star_grey3.png'),
  },
  ui: {
    panelBlue: assetPath('/game/panel_blue.png'),
    panelPurple: assetPath('/game/panel_purple.png'),
    panelWood: assetPath('/game/panel_wood.png'),
    buttonGreen: assetPath('/game/button_green.png'),
    buttonYellow: assetPath('/game/button_yellow.png'),
    ribbonBlue: assetPath('/game/ribbon_blue.png'),
    labelWood: assetPath('/game/label_wood.png'),
  },
  decor: {
    cloud: assetPath('/game/dec_cloud.png'),
    tree: assetPath('/game/dec_tree.png'),
    rock: assetPath('/game/dec_rock.png'),
    plant: assetPath('/game/dec_plant.png'),
    sparkle: assetPath('/game/dec_sparkle.png'),
    banner: assetPath('/game/dec_banner.png'),
  },
  menu: {
    bag: assetPath('/game/bag.png'),
    task: assetPath('/game/scroll.png'),
    achievement: assetPath('/game/badge_crown.png'),
    shop: assetPath('/game/icon_shop.png'),
    rank: assetPath('/game/badge_star.png'),
    settings: assetPath('/game/icon_settings.png'),
    mail: assetPath('/game/scroll.png'),
  },
  mic: {
    idle: assetPath('/game/mic_idle.png'),
    recording: assetPath('/game/mic_recording.png'),
    recognizing: assetPath('/game/mic_recognizing.png'),
    permissionFail: assetPath('/game/mic_permission_fail.png'),
    disconnected: assetPath('/game/mic_disconnected.png'),
  },
} as const

export type GameAssetLevelKey = keyof typeof gameAsset.levels
