export const gameAsset = {
  map: {
    large: '/game/map_large.png',
    small: '/game/map_small.png',
    backgrounds: {
      desktop: '/game/campaign-dynamic/map_background.png',
      tablet: '/game/campaign-dynamic/map_background.png',
      mobile: '/game/campaign-dynamic/map_background.png',
    },
    layers: {
      far: '/game/map_layer_far.png',
      mid: '/game/map_layer_mid.png',
      front: '/game/map_layer_front.png',
    },
    forest: '/game/map_forest.png',
    lake: '/game/map_lake.png',
    mountain: '/game/map_mountain.png',
    castle: '/game/map_castle.png',
    completed: '/game/map_completed.png',
    locked: '/game/map_locked.png',
    nodes: [
      '/game/map_node1.png',
      '/game/map_node2.png',
      '/game/map_node3.png',
      '/game/map_node4.png',
      '/game/map_node5.png',
    ],
  },
  levels: {
    spelling: '/game/level_card_spell.png',
    pronunciation: '/game/level_card_pronunciation.png',
    definition: '/game/level_card_definition.png',
    speaking: '/game/level_card_speaking.png',
    example: '/game/level_card_example.png',
  },
  scenes: {
    spelling: '/game/scene_spell.png',
    pronunciation: '/game/scene_pronunciation.png',
    definition: '/game/scene_definition.png',
    speaking: '/game/scene_speaking.png',
    example: '/game/scene_example.png',
  },
  icons: {
    spelling: '/game/icon_spelling.png',
    pronunciation: '/game/icon_pronunciation.png',
    definition: '/game/icon_definition.png',
    speaking: '/game/icon_speaking.png',
    example: '/game/icon_example.png',
    play: '/game/icon_play.png',
    pause: '/game/icon_pause.png',
    soundOn: '/game/icon_sound_on.png',
    home: '/game/icon_home.png',
    restart: '/game/icon_restart.png',
    current: '/game/icon_current.png',
    notebook: '/game/icon_notebook.png',
    reward: '/game/icon_reward.png',
    target: '/game/icon_target.png',
    settings: '/game/icon_settings.png',
    shop: '/game/icon_shop.png',
  },
  character: {
    boyIdle: '/game/hero_boy_idle.png',
    boyRun: '/game/hero_boy_run.png',
    boyCheer: '/game/hero_boy_cheer.png',
    girlStand: '/game/hero_girl_stand.png',
    teacher: '/game/bird_teacher_point_book.png',
    robot: '/game/robot_wave.png',
  },
  reward: {
    coin: '/game/coin.png',
    diamond: '/game/diamond.png',
    exp: '/game/exp.png',
    energy: '/game/energy.png',
    heart: '/game/heart.png',
    chestNormal: '/game/chest_normal.png',
    chestSapphire: '/game/chest_sapphire.png',
    chestGolden: '/game/chest_golden.png',
    chestSpecial: '/game/chest_special.png',
    star1: '/game/star1.png',
    star2: '/game/star2.png',
    star3: '/game/star3.png',
    starGrey1: '/game/star_grey1.png',
    starGrey2: '/game/star_grey2.png',
    starGrey3: '/game/star_grey3.png',
  },
  ui: {
    panelBlue: '/game/panel_blue.png',
    panelPurple: '/game/panel_purple.png',
    panelWood: '/game/panel_wood.png',
    buttonGreen: '/game/button_green.png',
    buttonYellow: '/game/button_yellow.png',
    ribbonBlue: '/game/ribbon_blue.png',
    labelWood: '/game/label_wood.png',
  },
  decor: {
    cloud: '/game/dec_cloud.png',
    tree: '/game/dec_tree.png',
    rock: '/game/dec_rock.png',
    plant: '/game/dec_plant.png',
    sparkle: '/game/dec_sparkle.png',
    banner: '/game/dec_banner.png',
  },
  menu: {
    bag: '/game/bag.png',
    task: '/game/scroll.png',
    achievement: '/game/badge_crown.png',
    shop: '/game/icon_shop.png',
    rank: '/game/badge_star.png',
    settings: '/game/icon_settings.png',
    mail: '/game/scroll.png',
  },
  mic: {
    idle: '/game/mic_idle.png',
    recording: '/game/mic_recording.png',
    recognizing: '/game/mic_recognizing.png',
    permissionFail: '/game/mic_permission_fail.png',
    disconnected: '/game/mic_disconnected.png',
  },
  campaignDynamic: {
    avatar: '/game/campaign-dynamic/avatar_portrait.png',
    levelPlaque: '/game/campaign-dynamic/level_plaque.png',
    titleScroll: '/game/campaign-dynamic/title_scroll_empty.png',
    progressPanel: '/game/campaign-dynamic/progress_panel.svg',
    actionButton: '/game/campaign-dynamic/button_action_empty.png',
    exitButton: '/game/wuwei-transparent-v3/buttons/button_exit.png',
    counters: {
      energy: '/game/campaign-dynamic/counter_energy.png',
      coin: '/game/campaign-dynamic/counter_coin.png',
      gem: '/game/campaign-dynamic/counter_gem.png',
    },
    mailButton: '/game/campaign-dynamic/mail_button.png',
    shields: {
      blue: '/game/campaign-dynamic/shield_blue.png',
      silver: '/game/campaign-dynamic/shield_silver.png',
      gold: '/game/campaign-dynamic/shield_gold.png',
    },
    battleNodes: {
      active: '/game/campaign-dynamic/battle_node_tower_active.png',
      locked: '/game/campaign-dynamic/battle_node_tower_locked.png',
      cleared: '/game/campaign-dynamic/battle_node_tower_cleared.png',
    },
    treasureChestBase: '/game/campaign-dynamic/treasure_chest.png',
    treasureChest: '/game/campaign-dynamic/treasure_chest_counter_frame.svg',
    starFull: '/game/campaign-dynamic/star_full.png',
    starEmpty: '/game/campaign-dynamic/star_empty.png',
    bossBadge: '/game/campaign-dynamic/boss_badge.png',
    recoveryBadge: '/game/campaign-dynamic/recovery_badge.png',
  },
} as const

export type GameAssetLevelKey = keyof typeof gameAsset.levels
