import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  bigBoard: {
    backgroundColor: '#FFFDF0', // Cream white
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    marginBottom: theme.spacing.lg,
    marginTop: theme.spacing.md,
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
    overflow: 'visible', // allow stickers to overflow
  },
  boardHeader: {
    marginBottom: theme.spacing.md,
  },
  boardTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
  },
  boardSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    marginTop: 2,
  },
  catSpeech: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    marginTop: -24,
    minHeight: 48,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  catSpeechText: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  catSpot: {
    alignItems: 'center',
    left: theme.spacing.xl,
    position: 'absolute',
    top: 140,
    zIndex: 10,
  },
  challengeBanner: {
    alignItems: 'center',
    backgroundColor: '#FF86A8',
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    justifyContent: 'center',
    left: 16,
    minHeight: 92,
    paddingHorizontal: theme.spacing.xs,
    position: 'absolute',
    top: 26,
    width: 48,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  challengeText: {
    color: '#5A2E1B',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  closeButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: theme.spacing.md,
    top: theme.spacing.md,
    width: 34,
  },
  feedbackButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    elevation: 2,
    justifyContent: 'center',
    minHeight: 54,
    marginTop: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  feedbackButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  feedbackHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.label,
    lineHeight: 20,
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
  feedbackSheet: {
    alignItems: 'center',
    backgroundColor: '#FFFDF0',
    borderColor: theme.colors.border,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 2,
    marginTop: 'auto',
    overflow: 'visible',
    padding: theme.spacing.xl,
  },
  feedbackTitle: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: '900',
    marginTop: theme.spacing.sm,
  },
  feedbackValue: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.title,
    fontWeight: '900',
    marginTop: theme.spacing.xs,
  },
  hangingLetter: {
    alignItems: 'center',
    backgroundColor: '#FFE7EF',
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    height: 48,
    justifyContent: 'center',
    left: '66%',
    position: 'absolute',
    top: 22,
    transform: [{ rotate: '9deg' }],
    width: 82,
    zIndex: 3,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  letterHeart: {
    color: theme.colors.rose,
    fontSize: 20,
    fontWeight: '900',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  objectIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  objectLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
  pawOne: {
    backgroundColor: 'rgba(243, 107, 154, 0.10)',
    borderRadius: theme.radius.pill,
    height: 78,
    left: 140,
    position: 'absolute',
    top: 70,
    width: 78,
  },
  pawTwo: {
    backgroundColor: 'rgba(243, 107, 154, 0.10)',
    borderRadius: theme.radius.pill,
    height: 92,
    position: 'absolute',
    right: 22,
    top: 215,
    width: 92,
  },
  planTicket: {
    alignItems: 'center',
    backgroundColor: '#FFFDF0',
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  railItem: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    marginBottom: theme.spacing.sm,
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: theme.spacing.sm,
    width: 76,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  railLabel: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '900',
    marginTop: 2,
    textAlign: 'center',
  },
  rightRail: {
    position: 'absolute',
    right: theme.spacing.sm,
    top: 82,
    zIndex: 4,
  },
  roomObject: {
    alignItems: 'center',
    width: '20%',
  },
  roomStatCell: {
    alignItems: 'center',
    flex: 1,
  },
  roomStatLabel: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    marginTop: 2,
  },
  roomStatValue: {
    color: theme.colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  roomStats: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    flexDirection: 'row',
    marginBottom: theme.spacing.md,
    padding: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  scene: {
    backgroundColor: '#FFE8EE', // Match theme background
    borderColor: theme.colors.border,
    borderRadius: 24,
    borderWidth: 2,
    height: 540,
    marginBottom: theme.spacing.md,
    overflow: 'hidden',
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  studyDesk: {
    alignItems: 'flex-end',
    backgroundColor: '#FFE7EF',
    borderTopColor: theme.colors.border,
    borderTopWidth: 2,
    bottom: 0,
    flexDirection: 'row',
    height: 128,
    justifyContent: 'space-around',
    left: 0,
    paddingBottom: theme.spacing.md,
    paddingHorizontal: theme.spacing.sm,
    position: 'absolute',
    right: 0,
  },
  ticketButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    elevation: 2,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  ticketButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  ticketEyebrow: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  ticketTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
    marginTop: 2,
  },
  todoCopy: {
    flex: 1,
  },
  todoCta: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  todoIndex: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    width: 28,
  },
  todoSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
  },
  todoTicket: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginBottom: theme.spacing.md,
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  todoTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  vipSticker: {
    alignItems: 'center',
    backgroundColor: '#FFD93D',
    borderColor: theme.colors.border,
    borderRadius: 24,
    borderWidth: 2,
    bottom: 118,
    minWidth: 120,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    position: 'absolute',
    right: 14,
    transform: [{ rotate: '-3deg' }],
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  vipStickerText: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  vipStickerTiny: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  windowFrame: {
    backgroundColor: '#F7FBF8',
    borderColor: '#5A3A26',
    borderRadius: theme.radius.card,
    borderWidth: 2,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    height: 174,
    left: 105,
    padding: theme.spacing.sm,
    position: 'absolute',
    right: 58,
    top: 80,
  },
  windowPane: {
    backgroundColor: '#DDF6F0',
    borderColor: '#AEC9BE',
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flex: 1,
  },
})
