import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  catSpeech: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    marginTop: -8,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
  },
  catSpeechText: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  catSpot: {
    alignItems: 'center',
    left: theme.spacing.lg,
    position: 'absolute',
    top: 168,
  },
  challengeBanner: {
    alignItems: 'center',
    backgroundColor: '#F6B6B6',
    borderColor: '#5A3A26',
    borderRadius: theme.radius.card,
    borderWidth: 2,
    justifyContent: 'center',
    left: 16,
    minHeight: 92,
    paddingHorizontal: theme.spacing.xs,
    position: 'absolute',
    top: 26,
    width: 48,
  },
  challengeText: {
    color: '#5A2E1B',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  closeButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: theme.spacing.md,
    top: theme.spacing.md,
    width: 34,
  },
  feedbackButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.control,
    justifyContent: 'center',
    minHeight: 48,
    marginTop: theme.spacing.lg,
  },
  feedbackButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  feedbackHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.label,
    lineHeight: 20,
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
  feedbackSheet: {
    alignItems: 'center',
    backgroundColor: '#FFF8ED',
    borderColor: '#F4CF97',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    marginTop: 'auto',
    overflow: 'visible',
    padding: theme.spacing.xl,
  },
  feedbackTitle: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: '900',
    marginTop: theme.spacing.sm,
  },
  feedbackValue: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.title,
    fontWeight: '900',
    marginTop: theme.spacing.xs,
  },
  hangingLetter: {
    alignItems: 'center',
    backgroundColor: '#FFE8EF',
    borderColor: '#5A3A26',
    borderRadius: theme.radius.card,
    borderWidth: 2,
    height: 44,
    justifyContent: 'center',
    left: '66%',
    position: 'absolute',
    top: 22,
    transform: [{ rotate: '9deg' }],
    width: 76,
    zIndex: 3,
  },
  letterHeart: {
    color: theme.colors.rose,
    fontSize: 20,
    fontWeight: '900',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  objectIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  objectLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
  pawOne: {
    backgroundColor: 'rgba(243, 107, 154, 0.10)',
    borderRadius: theme.radius.pill,
    height: 78,
    left: 140,
    position: 'absolute',
    top: 70,
    width: 78,
  },
  pawTwo: {
    backgroundColor: 'rgba(243, 107, 154, 0.10)',
    borderRadius: theme.radius.pill,
    height: 92,
    position: 'absolute',
    right: 22,
    top: 215,
    width: 92,
  },
  planTicket: {
    alignItems: 'center',
    backgroundColor: '#FFF8ED',
    borderColor: '#F4CF97',
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
    padding: theme.spacing.md,
  },
  railItem: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    marginBottom: theme.spacing.sm,
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: theme.spacing.sm,
    width: 72,
  },
  railLabel: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '900',
    marginTop: 2,
    textAlign: 'center',
  },
  rightRail: {
    position: 'absolute',
    right: theme.spacing.sm,
    top: 82,
    zIndex: 4,
  },
  roomObject: {
    alignItems: 'center',
    width: '20%',
  },
  roomStatCell: {
    alignItems: 'center',
    flex: 1,
  },
  roomStatLabel: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    marginTop: 2,
  },
  roomStatValue: {
    color: theme.colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  roomStats: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: theme.spacing.md,
    padding: theme.spacing.md,
  },
  scene: {
    backgroundColor: '#FFFDFB',
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    height: 540,
    marginBottom: theme.spacing.md,
    overflow: 'hidden',
  },
  studyDesk: {
    alignItems: 'flex-end',
    backgroundColor: '#F7CAD6',
    borderTopColor: '#E8B3C3',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 128,
    justifyContent: 'space-around',
    left: 0,
    paddingBottom: theme.spacing.md,
    paddingHorizontal: theme.spacing.sm,
    position: 'absolute',
    right: 0,
  },
  ticketButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.control,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: theme.spacing.lg,
  },
  ticketButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  ticketEyebrow: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  ticketTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
    marginTop: 2,
  },
  todoCopy: {
    flex: 1,
  },
  todoCta: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  todoIndex: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    width: 28,
  },
  todoSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
  },
  todoTicket: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  todoTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  vipSticker: {
    alignItems: 'center',
    backgroundColor: '#FF86A8',
    borderColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 3,
    bottom: 118,
    minWidth: 120,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    position: 'absolute',
    right: 14,
    transform: [{ rotate: '-3deg' }],
  },
  vipStickerText: {
    color: '#FFFFFF',
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  vipStickerTiny: {
    color: '#FFE7EF',
    fontSize: 11,
    fontWeight: '900',
  },
  windowFrame: {
    backgroundColor: '#F7FBF8',
    borderColor: '#5A3A26',
    borderRadius: theme.radius.card,
    borderWidth: 2,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    height: 174,
    left: 105,
    padding: theme.spacing.sm,
    position: 'absolute',
    right: 58,
    top: 80,
  },
  windowPane: {
    backgroundColor: '#DDF6F0',
    borderColor: '#AEC9BE',
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flex: 1,
  },
})
