import type { UsePracticePageActionsParams, UsePracticePageActionsResult } from './usePracticePageActions.types'
import { usePracticePageWrongWordActions } from './usePracticePageWrongWordActions'
import { usePracticeWordMasterySubmitter } from './usePracticeWordMasterySubmitter'
import { usePracticePageNavigationActions } from './usePracticePageNavigationActions'
import { usePracticePageAnswerActions } from './usePracticePageAnswerActions'

export function usePracticePageActions(params: UsePracticePageActionsParams): UsePracticePageActionsResult {
  const {
    user,
    userId,
    mode,
    smartDimension,
    bookId,
    chapterId,
    currentDay,
    currentWord,
    queue,
    queueIndex,
    correctCount,
    wrongCount,
    correctIndex,
    options,
    wrongSelections,
    choiceOptionsReady,
    showResult,
    spellingInput,
    spellingResult,
    errorMode,
    settings,
    navigate,
    showToast,
    playWord,
    saveProgress,
    clearSpellingRetryTimer,
    clearSpellingFeedbackDismissTimer,
    prepareSessionForLearningAction,
    completeCurrentSession,
    registerAnsweredWord,
    syncCurrentSessionSnapshot,
    lastState,
    setLastState,
    setPreviousWord,
    previousWord,
    setSelectedAnswer,
    setWrongSelections,
    setShowResult,
    setSpellingInput,
    setSpellingResult,
    setSpellingFeedbackLocked,
    setSpellingFeedbackDismissing,
    setSpellingFeedbackSnapshot,
    setQueue,
    setQueueIndex,
    setCorrectCount,
    setWrongCount,
    setWordStatuses,
    spellingRetryTimerRef,
    sessionIdRef,
    sessionCorrectRef,
    sessionWrongRef,
    completedSessionDurationSecondsRef,
    errorRoundResultsRef,
  } = params

  const {
    saveWrongWord,
    handleQuickMemoryRecordChange,
    recordErrorReviewOutcome,
  } = usePracticePageWrongWordActions({
    user,
    userId,
    mode,
    smartDimension,
    bookId,
    chapterId,
    errorMode,
    showToast,
    errorRoundResultsRef,
  })

  const submitPracticeWordMastery = usePracticeWordMasterySubmitter({
    userId,
    bookId,
    chapterId,
    currentDay,
    currentWord,
    errorMode,
    sessionIdRef,
  })

  const { goBack, goNext } = usePracticePageNavigationActions({
    chapterId,
    completeCurrentSession,
    completedSessionDurationSecondsRef,
    correctCount,
    currentWord,
    errorMode,
    lastState,
    navigate,
    previousWord,
    queue,
    queueIndex,
    setCorrectCount,
    setLastState,
    setPreviousWord,
    setQueue,
    setQueueIndex,
    setSelectedAnswer,
    setShowResult,
    setSpellingFeedbackDismissing,
    setSpellingFeedbackLocked,
    setSpellingFeedbackSnapshot,
    setSpellingInput,
    setSpellingResult,
    setWrongCount,
    setWrongSelections,
    settings,
    wrongCount,
  })

  const {
    handleOptionSelect,
    handleSpellingSubmit,
    handleMeaningRecallSubmit,
    handleFollowReadEvaluated,
    handleSkip,
  } = usePracticePageAnswerActions({
    mode,
    smartDimension,
    currentWord,
    queue,
    queueIndex,
    correctCount,
    wrongCount,
    correctIndex,
    options,
    wrongSelections,
    choiceOptionsReady,
    showResult,
    spellingInput,
    spellingResult,
    playWord,
    saveProgress,
    clearSpellingRetryTimer,
    clearSpellingFeedbackDismissTimer,
    prepareSessionForLearningAction,
    registerAnsweredWord,
    syncCurrentSessionSnapshot,
    setSelectedAnswer,
    setWrongSelections,
    setShowResult,
    setSpellingInput,
    setSpellingResult,
    setSpellingFeedbackLocked,
    setSpellingFeedbackDismissing,
    setSpellingFeedbackSnapshot,
    setCorrectCount,
    setWrongCount,
    setWordStatuses,
    spellingRetryTimerRef,
    sessionCorrectRef,
    sessionWrongRef,
    goNext,
    saveWrongWord,
    recordErrorReviewOutcome,
    submitPracticeWordMastery,
  })

  return {
    saveWrongWord,
    handleQuickMemoryRecordChange,
    recordErrorReviewOutcome,
    goBack,
    handleOptionSelect,
    handleSpellingSubmit,
    handleMeaningRecallSubmit,
    handleFollowReadEvaluated,
    handleSkip,
  }
}
